/**
 * Take-Over trusted input (§4.8): the in-sandbox helper that turns a live-view
 * click/key/scroll into REAL browser input via CDP `Input.dispatch*`, plus the
 * command builders the provider runs.
 *
 * Why CDP and not DOM synthesis: the previous relay ran
 * `document.elementFromPoint(x,y)?.click()` through `agent-browser eval` — an
 * untrusted (`isTrusted: false`) event that bot checks ignore, that cannot
 * reach into cross-origin iframes (reCAPTCHA's checkbox lives in one; the
 * top document only sees the <iframe> node), and that never moves focus, so
 * follow-up keystrokes had no target. CDP input events enter through the
 * browser's real input pipeline: trusted, iframe-transparent, focus-moving.
 *
 * The helper is dependency-free Node (the template bakes Node 22 for
 * agent-browser; global WebSocket + fetch ship with it) and is written into
 * the sandbox once per task. Each event is one short-lived invocation:
 *   node <helper> <cdp-endpoint> <event-json>
 * The endpoint comes from `agent-browser get cdp-url` (validated in-sandbox
 * 2026-07-13) — http(s) endpoints are resolved to the browser WebSocket via
 * /json/version.
 *
 * Coordinate space: frames come from `agent-browser screenshot` (viewport at
 * the template's DPR of 1), and CDP takes CSS-viewport pixels — 1:1 with the
 * frame, so the provider forwards coordinates unscaled.
 *
 * [COMP:sandbox/e2b-cloud] — spec: docs/architecture/engine/computer-use.md §4.8.
 */

export const TAKEOVER_INPUT_HELPER_PATH = '/home/user/.agent-browser/takeover-input.mjs'

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

/** The provider-side command line for one input event. */
export function takeoverInputCommand(cdpEndpoint: string, eventJson: string): string {
  return `node ${TAKEOVER_INPUT_HELPER_PATH} ${shellQuote(cdpEndpoint)} ${shellQuote(eventJson)}`
}

/**
 * The helper source. Named keys the page can meaningfully forward map to CDP
 * key events (Enter carries text "\r" — form submits listen for it); single
 * characters insert as text (IME-safe, no layout mapping needed); anything
 * else (modifiers, F-keys, Dead) exits 0 as a deliberate no-op so the relay
 * never 502s on harmless keys.
 */
export const TAKEOVER_INPUT_HELPER_MJS = `// Take-Over trusted input dispatcher (generated by Use Brian — do not edit).
const [, , endpoint, eventJson] = process.argv
if (!endpoint || !eventJson) {
  console.error('usage: takeover-input.mjs <cdp-endpoint> <event-json>')
  process.exit(2)
}
const event = JSON.parse(eventJson)
const deadline = setTimeout(() => { console.error('cdp dispatch timed out'); process.exit(2) }, 8000)

const KEYS = {
  Enter: { key: 'Enter', code: 'Enter', windowsVirtualKeyCode: 13, text: '\\r' },
  Tab: { key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9 },
  Backspace: { key: 'Backspace', code: 'Backspace', windowsVirtualKeyCode: 8 },
  Delete: { key: 'Delete', code: 'Delete', windowsVirtualKeyCode: 46 },
  Escape: { key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 },
  ArrowLeft: { key: 'ArrowLeft', code: 'ArrowLeft', windowsVirtualKeyCode: 37 },
  ArrowUp: { key: 'ArrowUp', code: 'ArrowUp', windowsVirtualKeyCode: 38 },
  ArrowRight: { key: 'ArrowRight', code: 'ArrowRight', windowsVirtualKeyCode: 39 },
  ArrowDown: { key: 'ArrowDown', code: 'ArrowDown', windowsVirtualKeyCode: 40 },
  Home: { key: 'Home', code: 'Home', windowsVirtualKeyCode: 36 },
  End: { key: 'End', code: 'End', windowsVirtualKeyCode: 35 },
  PageUp: { key: 'PageUp', code: 'PageUp', windowsVirtualKeyCode: 33 },
  PageDown: { key: 'PageDown', code: 'PageDown', windowsVirtualKeyCode: 34 },
}

async function wsUrlFrom(raw) {
  if (raw.startsWith('ws://') || raw.startsWith('wss://')) return raw
  const res = await fetch(new URL('/json/version', raw))
  const info = await res.json()
  if (!info.webSocketDebuggerUrl) throw new Error('no webSocketDebuggerUrl at ' + raw)
  return info.webSocketDebuggerUrl
}

const ws = new WebSocket(await wsUrlFrom(endpoint))
let nextId = 1
const pending = new Map()
function send(method, params, sessionId) {
  const id = nextId++
  const msg = { id, method, params: params ?? {} }
  if (sessionId) msg.sessionId = sessionId
  ws.send(JSON.stringify(msg))
  return new Promise((resolve, reject) => pending.set(id, { resolve, reject }))
}
ws.onmessage = (m) => {
  const data = JSON.parse(typeof m.data === 'string' ? m.data : m.data.toString())
  if (data.id && pending.has(data.id)) {
    const p = pending.get(data.id)
    pending.delete(data.id)
    if (data.error) p.reject(new Error(data.error.message))
    else p.resolve(data.result)
  }
}
ws.onerror = () => { console.error('cdp socket error'); process.exit(2) }

ws.onopen = async () => {
  try {
    const { targetInfos } = await send('Target.getTargets')
    const pages = targetInfos.filter((t) => t.type === 'page' && !t.url.startsWith('devtools://'))
    const target = pages[pages.length - 1]
    if (!target) throw new Error('no page target')
    const { sessionId } = await send('Target.attachToTarget', { targetId: target.targetId, flatten: true })

    if (event.kind === 'click') {
      const base = { x: event.x, y: event.y, button: 'left', clickCount: 1, pointerType: 'mouse' }
      await send('Input.dispatchMouseEvent', { ...base, type: 'mouseMoved', button: 'none' }, sessionId)
      await send('Input.dispatchMouseEvent', { ...base, type: 'mousePressed' }, sessionId)
      await send('Input.dispatchMouseEvent', { ...base, type: 'mouseReleased' }, sessionId)
    } else if (event.kind === 'key') {
      if (event.text.length === 1) {
        await send('Input.insertText', { text: event.text }, sessionId)
      } else if (KEYS[event.text]) {
        const def = KEYS[event.text]
        await send('Input.dispatchKeyEvent', { type: 'keyDown', ...def }, sessionId)
        await send('Input.dispatchKeyEvent', { type: 'keyUp', key: def.key, code: def.code, windowsVirtualKeyCode: def.windowsVirtualKeyCode }, sessionId)
      } // unknown named key → deliberate no-op
    } else if (event.kind === 'scroll') {
      const metrics = await send('Page.getLayoutMetrics', {}, sessionId)
      const vp = metrics.cssVisualViewport ?? metrics.visualViewport ?? { clientWidth: 1280, clientHeight: 720 }
      await send('Input.dispatchMouseEvent', {
        type: 'mouseWheel',
        x: Math.round(vp.clientWidth / 2),
        y: Math.round(vp.clientHeight / 2),
        deltaX: 0,
        deltaY: event.deltaY,
        pointerType: 'mouse',
      }, sessionId)
    }
    clearTimeout(deadline)
    ws.close()
    process.exit(0)
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err))
    process.exit(2)
  }
}
`
