/**
 * Take-Over live stream (§5 "live stream, not a screenshot poll"): the
 * in-sandbox bridge source + the provider-side commands that enable
 * agent-browser's built-in screencast stream and launch the bridge.
 *
 * Why a bridge: E2B's ingress completes WebSocket/SSE upgrades only against
 * 0.0.0.0-bound listeners (probed 2026-07-15 — the loopback-bound stream
 * server serves plain HTTP through the ingress but fails WS upgrades), and
 * agent-browser's stream server carries no auth. The bridge adds both in one
 * dependency-free Node process: it is the ONLY exposed listener, it checks a
 * per-sandbox token in constant time, and the stream server + CDP stay
 * loopback-only behind it.
 *
 *   browser ──SSE──▶ 0.0.0.0:49223 /frames?token=…   (JPEG frame events)
 *   browser ──POST─▶ 0.0.0.0:49223 /input?token=…    (click/key/scroll)
 *                        │
 *                        ├─ WS client → 127.0.0.1:49222 (agent-browser
 *                        │  screencast; attached only while a viewer is
 *                        │  connected — no viewer, no encoding cost)
 *                        └─ ONE persistent CDP connection (same trusted
 *                           Input.dispatch* vocabulary as takeover-input.ts,
 *                           minus the per-event process spawn)
 *
 * [COMP:sandbox/takeover-stream] — spec: docs/architecture/engine/computer-use.md §5.
 */

/** agent-browser's screencast WS server — loopback-only, never exposed. */
export const TAKEOVER_STREAM_PORT = 49222
/** The bridge's public listener (0.0.0.0 — the one E2B-ingress-facing port). */
export const TAKEOVER_BRIDGE_PORT = 49223

export const TAKEOVER_STREAM_BRIDGE_PATH = '/home/user/.agent-browser/takeover-stream-bridge.mjs'
const BRIDGE_LOG_PATH = '/tmp/takeover-bridge.log'

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

/** Idempotent stream (re)pin: a fixed port the bridge can always find. */
export function streamEnableCommand(): string {
  return `agent-browser stream disable >/dev/null 2>&1; agent-browser stream enable --port ${TAKEOVER_STREAM_PORT}`
}

/**
 * Detached launch — every fd off the exec session so envd does not hold the
 * command open, `setsid` so the bridge survives the session. Idempotent by
 * listener: a second launch exits immediately on EADDRINUSE.
 */
export function bridgeLaunchCommand(token: string, cdpEndpoint: string): string {
  return (
    `setsid nohup node ${TAKEOVER_STREAM_BRIDGE_PATH} ` +
    `--port ${TAKEOVER_BRIDGE_PORT} --stream ws://127.0.0.1:${TAKEOVER_STREAM_PORT} ` +
    `--cdp ${shellQuote(cdpEndpoint)} --token ${shellQuote(token)} ` +
    `</dev/null >>${BRIDGE_LOG_PATH} 2>&1 & echo launched`
  )
}

/** Fast liveness probe for the bridge listener (retried by the provider). */
export function bridgeProbeCommand(): string {
  return `ss -ltn 2>/dev/null | grep -c :${TAKEOVER_BRIDGE_PORT}`
}

/**
 * The bridge source (generated file — dependency-free Node 22: global
 * WebSocket + node:http + node:crypto only, the same constraint as
 * takeover-input.ts). Input vocabulary and CDP dispatch mirror
 * takeover-input.ts — keep the two in lockstep when the event shape moves.
 */
export const TAKEOVER_STREAM_BRIDGE_MJS = `// Take-Over live-stream bridge (generated by Use Brian — do not edit).
import http from 'node:http'
import crypto from 'node:crypto'

const args = {}
for (let i = 2; i < process.argv.length; i += 2) args[process.argv[i].replace(/^--/, '')] = process.argv[i + 1]
const PORT = Number(args.port)
const STREAM_URL = args.stream
const CDP_ENDPOINT = args.cdp
const TOKEN = args.token || ''
if (!PORT || !STREAM_URL || !CDP_ENDPOINT || !TOKEN) {
  console.error('usage: takeover-stream-bridge.mjs --port N --stream ws://… --cdp <endpoint> --token <hex>')
  process.exit(2)
}

function tokenOk(candidate) {
  const a = crypto.createHash('sha256').update(String(candidate ?? '')).digest()
  const b = crypto.createHash('sha256').update(TOKEN).digest()
  return crypto.timingSafeEqual(a, b)
}

// ── screencast leg: attach to agent-browser's stream only while watched ──
const clients = new Set()
let latestFrame = null
let streamWs = null
let streamWanted = false

function attachStream() {
  streamWanted = true
  if (streamWs) return
  const ws = new WebSocket(STREAM_URL)
  streamWs = ws
  ws.onmessage = (ev) => {
    const text = typeof ev.data === 'string' ? ev.data : null
    if (!text) return
    const isFrame = text.includes('"data":')
    if (isFrame) latestFrame = text
    for (const c of clients) c.push(isFrame ? 'frame' : 'meta', text)
  }
  const drop = () => {
    if (streamWs === ws) streamWs = null
    if (streamWanted && clients.size > 0) setTimeout(attachStream, 500)
  }
  ws.onclose = drop
  ws.onerror = drop
}
function detachStreamIfIdle() {
  if (clients.size > 0) return
  streamWanted = false
  if (streamWs) { try { streamWs.close() } catch {} streamWs = null }
}

// ── input leg: one persistent CDP connection, re-attached on failure ──
const KEYS = {
  Enter: { key: 'Enter', code: 'Enter', windowsVirtualKeyCode: 13, text: '\\r' },
  Tab: { key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9 },
  Backspace: { key: 'Backspace', code: 'Backspace', windowsVirtualKeyCode: 8 },
  Delete: { key: 'Delete', code: 'Delete', windowsVirtualKeyCode: 46 },
  Escape: { key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 },
  ArrowLeft: { key: 'ArrowLeft', code: 'ArrowLeft', windowsVirtualKeyCode: 37 },
  ArrowUp: { key: 'ArrowUp', code: 'ArrowUp', windowsVirtualKeyCode: 38 },
  ArrowRight: { key: 'ArrowRight', code: 'ArrowRight', windowsVirtualKeyCode: 39 },
  ArrowDown: { key: 'ArrowDown', code: 'ArrowDown', windowsVirtualKeyCode: 40 },
  Home: { key: 'Home', code: 'Home', windowsVirtualKeyCode: 36 },
  End: { key: 'End', code: 'End', windowsVirtualKeyCode: 35 },
  PageUp: { key: 'PageUp', code: 'PageUp', windowsVirtualKeyCode: 33 },
  PageDown: { key: 'PageDown', code: 'PageDown', windowsVirtualKeyCode: 34 },
}

let cdp = null // { ws, sessionId, nextId, pending }
async function wsUrlFrom(raw) {
  if (raw.startsWith('ws://') || raw.startsWith('wss://')) return raw
  const res = await fetch(new URL('/json/version', raw))
  const info = await res.json()
  if (!info.webSocketDebuggerUrl) throw new Error('no webSocketDebuggerUrl at ' + raw)
  return info.webSocketDebuggerUrl
}
function cdpSend(conn, method, params, sessionId) {
  const id = conn.nextId++
  const msg = { id, method, params: params ?? {} }
  if (sessionId) msg.sessionId = sessionId
  conn.ws.send(JSON.stringify(msg))
  return new Promise((resolve, reject) => {
    conn.pending.set(id, { resolve, reject })
    setTimeout(() => { if (conn.pending.delete(id)) reject(new Error('cdp timeout')) }, 8000)
  })
}
async function cdpConnect() {
  const ws = new WebSocket(await wsUrlFrom(CDP_ENDPOINT))
  const conn = { ws, sessionId: null, nextId: 1, pending: new Map() }
  await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = () => reject(new Error('cdp connect failed')) })
  ws.onmessage = (m) => {
    const data = JSON.parse(typeof m.data === 'string' ? m.data : m.data.toString())
    if (data.id && conn.pending.has(data.id)) {
      const p = conn.pending.get(data.id)
      conn.pending.delete(data.id)
      if (data.error) p.reject(new Error(data.error.message))
      else p.resolve(data.result)
    }
  }
  ws.onclose = () => { if (cdp === conn) cdp = null }
  ws.onerror = () => { if (cdp === conn) cdp = null }
  const { targetInfos } = await cdpSend(conn, 'Target.getTargets')
  const pages = targetInfos.filter((t) => t.type === 'page' && !t.url.startsWith('devtools://'))
  const target = pages[pages.length - 1]
  if (!target) throw new Error('no page target')
  const { sessionId } = await cdpSend(conn, 'Target.attachToTarget', { targetId: target.targetId, flatten: true })
  conn.sessionId = sessionId
  return conn
}
async function dispatchInput(event, retried) {
  try {
    if (!cdp) cdp = await cdpConnect()
    const conn = cdp
    const sid = conn.sessionId
    if (event.kind === 'click') {
      const base = { x: event.x, y: event.y, button: 'left', clickCount: 1, pointerType: 'mouse' }
      await cdpSend(conn, 'Input.dispatchMouseEvent', { ...base, type: 'mouseMoved', button: 'none' }, sid)
      await cdpSend(conn, 'Input.dispatchMouseEvent', { ...base, type: 'mousePressed' }, sid)
      await cdpSend(conn, 'Input.dispatchMouseEvent', { ...base, type: 'mouseReleased' }, sid)
    } else if (event.kind === 'key') {
      if (typeof event.text !== 'string' || event.text.length === 0) return
      if (event.text.length === 1) {
        await cdpSend(conn, 'Input.insertText', { text: event.text }, sid)
      } else if (KEYS[event.text]) {
        const def = KEYS[event.text]
        await cdpSend(conn, 'Input.dispatchKeyEvent', { type: 'keyDown', ...def }, sid)
        await cdpSend(conn, 'Input.dispatchKeyEvent', { type: 'keyUp', key: def.key, code: def.code, windowsVirtualKeyCode: def.windowsVirtualKeyCode }, sid)
      } // unknown named key → deliberate no-op
    } else if (event.kind === 'scroll') {
      const metrics = await cdpSend(conn, 'Page.getLayoutMetrics', {}, sid)
      const vp = metrics.cssVisualViewport ?? metrics.visualViewport ?? { clientWidth: 1280, clientHeight: 720 }
      await cdpSend(conn, 'Input.dispatchMouseEvent', {
        type: 'mouseWheel',
        x: Math.round(vp.clientWidth / 2),
        y: Math.round(vp.clientHeight / 2),
        deltaX: 0,
        deltaY: event.deltaY,
        pointerType: 'mouse',
      }, sid)
    }
  } catch (err) {
    cdp = null // page target may have navigated/died — re-attach once
    if (!retried) return dispatchInput(event, true)
    throw err
  }
}

// ── the one exposed listener ──
const server = http.createServer((req, res) => {
  const url = new URL(req.url, 'http://x')
  res.setHeader('Access-Control-Allow-Origin', '*')
  if (req.method === 'OPTIONS') {
    res.writeHead(204, { 'Access-Control-Allow-Methods': 'GET, POST', 'Access-Control-Allow-Headers': 'content-type' })
    res.end()
    return
  }
  if (!tokenOk(url.searchParams.get('token'))) { res.writeHead(403); res.end(); return }

  if (req.method === 'GET' && url.pathname === '/frames') {
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-store',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no',
    })
    const client = {
      stale: null,
      push(kind, text) {
        // Latest-frame-wins under backpressure: never queue stale pixels.
        if (res.writableLength > 512 * 1024) { if (kind === 'frame') this.stale = text; return }
        res.write('event: ' + kind + '\\n' + 'data: ' + text + '\\n\\n')
      },
    }
    res.on('drain', () => { if (client.stale) { const t = client.stale; client.stale = null; client.push('frame', t) } })
    clients.add(client)
    attachStream()
    if (latestFrame) client.push('frame', latestFrame)
    const ping = setInterval(() => res.write(': ping\\n\\n'), 15000)
    req.on('close', () => { clearInterval(ping); clients.delete(client); detachStreamIfIdle() })
    return
  }

  if (req.method === 'POST' && url.pathname === '/input') {
    let body = ''
    req.on('data', (c) => { body += c; if (body.length > 65536) req.destroy() })
    req.on('end', async () => {
      try {
        await dispatchInput(JSON.parse(body), false)
        res.writeHead(204)
        res.end()
      } catch (err) {
        res.writeHead(502, { 'Content-Type': 'application/json' })
        res.end(JSON.stringify({ error: String(err && err.message ? err.message : err).slice(0, 300) }))
      }
    })
    return
  }

  res.writeHead(404)
  res.end()
})
server.on('error', (err) => {
  // Another bridge already owns the port — this launch is the idempotent loser.
  if (err && err.code === 'EADDRINUSE') process.exit(0)
  console.error(String(err))
  process.exit(1)
})
server.listen(PORT, '0.0.0.0', () => console.log('takeover-stream-bridge on ' + PORT))
`
