export { createEmailAdapter } from './adapter.js'
export type { EmailAdapterOptions, EmailSendPort, EmailWebhookMessage } from './adapter.js'
export { parseEmailAddress, parseEmailDisplayName, isNoReplyAddress } from './address.js'
export { renderEmailBody, markdownToEmailHtml } from './markdown.js'
export type { EmailBody } from './markdown.js'
