/**
 * askQuestion suspend-resume — engine branch coverage.
 *
 * Component tag: [COMP:engine/askquestion-suspend].
 * Spec: docs/architecture/engine/askquestion-suspend-resume.md.
 *
 * Four code paths to verify:
 *   1. SUSPEND: questionResumeEnabled + createPendingQuestion hook +
 *      sole askQuestion + no workers → emits tool_confirmation_required
 *      + awaiting_approval, NO turn_complete (session is durable-paused).
 *   2. TERMINAL fallback: questionResumeEnabled but no hook → legacy
 *      behavior, fires turn_complete.
 *   3. TERMINAL legacy: questionResumeEnabled=false (worker, scheduled
 *      job, smoke test) → legacy behavior, fires turn_complete.
 *   4. STRIP (misuse): sole askQuestion BUT workers pending → strip the
 *      askQuestion as a no-op, loop continues (does not suspend, does
 *      not terminate).
 */

import { describe, it, expect, vi } from 'vitest'
import { z } from 'zod'
import type {
  LLMProvider,
  ProviderSession,
  SendOptions,
  SessionOptions,
  StreamChunk,
  Message,
} from '../../providers/types.js'
import { buildTool } from '../../tools/types.js'
import type { ToolContext } from '../../tools/types.js'
import { queryLoop, type QueryEvent } from '../query-loop.js'

const askQuestionTool = buildTool({
  name: 'askQuestion',
  description: 'Ask the user a question',
  inputSchema: z.object({ question: z.string() }),
  isConcurrencySafe: true,
  isReadOnly: true,
  async execute(input) {
    return { data: `[Question for user]: ${input.question}` }
  },
})

const baseContext: ToolContext = {
  userId: 'u',
  assistantId: 'a',
  sessionId: 's',
  appId: 'test',
  channelType: 'web',
  channelId: 'c',
  abortSignal: new AbortController().signal,
}

type TurnScript =
  | { kind: 'chunks'; chunks: StreamChunk[] }

function scriptedProvider(scripts: TurnScript[]): LLMProvider {
  let turn = 0
  function next(): AsyncIterable<StreamChunk> {
    const script = scripts[Math.min(turn, scripts.length - 1)]
    turn++
    return (async function* () {
      for (const chunk of script.chunks) yield chunk
    })()
  }
  const session: ProviderSession = {
    send(_messages: Message[], _opts?: SendOptions) { return next() },
  }
  return {
    name: 'scripted',
    models: ['mock-model'],
    stream: () => next(),
    createSession: (_o: SessionOptions) => session,
  }
}

// One-turn script that emits a single askQuestion tool call. The
// matching tool_result is generated by the executor at run time, so the
// queryLoop sees a complete sole-askQuestion turn and exercises the
// suspend / terminal branches at the Phase 4 decision point.
function askQuestionTurn(question: string, id = 'call_q1'): TurnScript {
  return {
    kind: 'chunks',
    chunks: [
      { type: 'message_start', model: 'mock-model' },
      { type: 'tool_use_start', id, name: 'askQuestion' },
      { type: 'tool_use_delta', id, input: JSON.stringify({ question }) },
      { type: 'tool_use_end', id },
      { type: 'message_end', stopReason: 'tool_use', usage: { inputTokens: 5, outputTokens: 3 } },
    ],
  }
}

async function runLoop(opts: {
  provider: LLMProvider
  context?: ToolContext
  questionResumeEnabled?: boolean
}): Promise<QueryEvent[]> {
  const events: QueryEvent[] = []
  for await (const e of queryLoop({
    provider: opts.provider,
    model: 'mock-model',
    systemPrompt: 'sys',
    messages: [{ role: 'user', content: 'hello' }],
    tools: new Map([['askQuestion', askQuestionTool]]),
    context: opts.context ?? baseContext,
    maxTurns: 5,
    ...(opts.questionResumeEnabled !== undefined
      ? { questionResumeEnabled: opts.questionResumeEnabled }
      : {}),
  })) {
    events.push(e)
  }
  return events
}

describe('[COMP:engine/askquestion-suspend] suspend branch', () => {
  it('suspends the loop when questionResumeEnabled + createPendingQuestion are both set', async () => {
    const createPendingQuestion = vi.fn().mockResolvedValue('appr_abc')
    const events = await runLoop({
      provider: scriptedProvider([askQuestionTurn('Which MeshJS?')]),
      context: { ...baseContext, createPendingQuestion },
      questionResumeEnabled: true,
    })

    // Persistence hook called with the question and a non-empty toolUseId.
    expect(createPendingQuestion).toHaveBeenCalledTimes(1)
    const call = createPendingQuestion.mock.calls[0]?.[0] as {
      question: string
      toolUseId: string
      expiresAt: Date
    }
    expect(call.question).toBe('Which MeshJS?')
    expect(call.toolUseId).toBe('call_q1')
    expect(call.expiresAt).toBeInstanceOf(Date)
    // 24h TTL — give it ±60s of clock jitter.
    const ttl = call.expiresAt.getTime() - Date.now()
    expect(ttl).toBeGreaterThan(24 * 60 * 60 * 1000 - 60_000)
    expect(ttl).toBeLessThan(24 * 60 * 60 * 1000 + 60_000)

    // tool_confirmation_required fired with the approvalId from the hook.
    const conf = events.find((e) => e.type === 'tool_confirmation_required')
    expect(conf).toBeDefined()
    if (conf?.type === 'tool_confirmation_required') {
      expect(conf.request.approvalId).toBe('appr_abc')
      expect(conf.request.toolName).toBe('askQuestion')
      expect(conf.request.toolCallId).toBe('call_q1')
      expect(conf.request.description).toBe('Which MeshJS?')
    }

    // awaiting_approval fired as the durability marker.
    const awaiting = events.find((e) => e.type === 'awaiting_approval')
    expect(awaiting).toBeDefined()
    if (awaiting?.type === 'awaiting_approval') {
      expect(awaiting.approvalId).toBe('appr_abc')
      expect(awaiting.toolName).toBe('askQuestion')
      expect(awaiting.toolCallId).toBe('call_q1')
    }

    // NO turn_complete — the suspended-loop invariant.
    expect(events.some((e) => e.type === 'turn_complete')).toBe(false)
  })

  it('falls back to terminal exit when the createPendingQuestion hook is absent', async () => {
    const events = await runLoop({
      provider: scriptedProvider([askQuestionTurn('Where do we go?')]),
      context: baseContext, // no createPendingQuestion
      questionResumeEnabled: true,
    })

    // No suspend events.
    expect(events.some((e) => e.type === 'tool_confirmation_required')).toBe(false)
    expect(events.some((e) => e.type === 'awaiting_approval')).toBe(false)

    // Terminal: turn_complete fires + question text streams to UI.
    expect(events.some((e) => e.type === 'turn_complete')).toBe(true)
    expect(
      events.some(
        (e) => e.type === 'text_delta' && e.text === 'Where do we go?',
      ),
    ).toBe(true)
  })

  it('keeps legacy terminal behavior when questionResumeEnabled is unset (worker / smoke context)', async () => {
    const createPendingQuestion = vi.fn().mockResolvedValue('appr_unused')
    const events = await runLoop({
      provider: scriptedProvider([askQuestionTurn('Legacy?')]),
      context: { ...baseContext, createPendingQuestion },
      // questionResumeEnabled omitted (default false)
    })

    // Hook is NOT invoked when the opt-in is off.
    expect(createPendingQuestion).not.toHaveBeenCalled()
    // Terminal exit fires.
    expect(events.some((e) => e.type === 'turn_complete')).toBe(true)
  })

  it('falls back to terminal exit when createPendingQuestion throws (persistence failure)', async () => {
    const createPendingQuestion = vi
      .fn()
      .mockRejectedValueOnce(new Error('db down'))
    const events = await runLoop({
      provider: scriptedProvider([askQuestionTurn('DB-broke?')]),
      context: { ...baseContext, createPendingQuestion },
      questionResumeEnabled: true,
    })

    expect(createPendingQuestion).toHaveBeenCalledTimes(1)
    // Suspend events not emitted on failure.
    expect(events.some((e) => e.type === 'tool_confirmation_required')).toBe(false)
    expect(events.some((e) => e.type === 'awaiting_approval')).toBe(false)
    // Falls back to terminal behavior so the user isn't left hanging.
    expect(events.some((e) => e.type === 'turn_complete')).toBe(true)
  })
})

describe('[COMP:engine/askquestion-suspend] misuse strip branch', () => {
  it('strips askQuestion when workers are still pending (status-narration misuse)', async () => {
    // Build a workerManager stub that reports a pending worker on the
    // first peek (so the engine sees "sole tool + workers pending"
    // → strip) then reports zero on subsequent peeks (so Phase 4b's
    // drain loop exits immediately instead of spinning).
    let pendingCount = 1
    const wm = {
      get pendingCount() { return pendingCount },
      get hasNotifications() { return false },
      pendingCountFor: () => pendingCount,
      hasNotificationsFor: () => false,
      get activeCount() { return pendingCount },
      get maxConcurrent() { return null },
      reset: vi.fn(),
      setOnEvent: vi.fn(),
      setResearchMode: vi.fn(),
      setResearchModel: vi.fn(),
      setMaxConcurrent: vi.fn(),
      spawn: vi.fn(),
      stop: vi.fn(),
      getStatus: vi.fn(),
      getDescription: vi.fn(),
      getResult: vi.fn(),
      drainNotifications: vi.fn().mockReturnValue([]),
      waitForNext: vi.fn().mockImplementation(async () => { pendingCount = 0 }),
      waitAll: vi.fn().mockResolvedValue([]),
      formatNotification: vi.fn().mockReturnValue(''),
    }
    const createPendingQuestion = vi.fn().mockResolvedValue('should-not-be-called')

    // One turn: askQuestion misuse. After strip, Phase 4b drain runs once
    // (pendingCount goes 1→0), no notifications to inject, loop falls
    // through to turn_complete on the same turn.
    const events = await runLoop({
      provider: scriptedProvider([askQuestionTurn('Please wait while I work')]),
      context: {
        ...baseContext,
        createPendingQuestion,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        workerManager: wm as any,
      },
      questionResumeEnabled: true,
    })

    // The askQuestion was STRIPPED — no suspend, no surface to user.
    expect(createPendingQuestion).not.toHaveBeenCalled()
    expect(events.some((e) => e.type === 'tool_confirmation_required')).toBe(false)
    expect(events.some((e) => e.type === 'awaiting_approval')).toBe(false)

    // The strip must retract the already-streamed tool step so the client's
    // tool timeline doesn't keep a phantom "Asking a question" entry.
    const dropped = events.find((e) => e.type === 'tool_dropped')
    expect(dropped).toBeDefined()
    if (dropped && dropped.type === 'tool_dropped') {
      expect(dropped.id).toBe('call_q1')
      expect(dropped.reason).toBe('askquestion_misuse')
    }

    // Loop exited normally via turn_complete.
    expect(events.some((e) => e.type === 'turn_complete')).toBe(true)
  })

  it('does NOT emit tool_dropped on the suspend (real-question) path', async () => {
    // Sole askQuestion + no workers + suspend-capable → suspends, does not
    // strip. The streamed step is a legitimate pending question, so there is
    // nothing to retract.
    const events = await runLoop({
      provider: scriptedProvider([askQuestionTurn('Which MeshJS?')]),
      context: {
        ...baseContext,
        createPendingQuestion: vi.fn().mockResolvedValue('appr_abc'),
      },
      questionResumeEnabled: true,
    })

    expect(events.some((e) => e.type === 'tool_dropped')).toBe(false)
    expect(events.some((e) => e.type === 'awaiting_approval')).toBe(true)
  })
})
