export type { KnowledgeStoreInterface, KnowledgeSearchResult, KnowledgeEntryDetail, KnowledgeRepoWriter, KnowledgeRepoWriteResult } from './types.js'
export { computeSimilarity } from './similarity.js'
export { createKnowledgeSyncWorker } from './sync-worker.js'
export type { SyncGitHubApi, SyncStore, SyncCredentials, SyncSource, SyncEvent } from './sync-worker.js'
export { parseMarkdownFile, normalisePath } from './parser.js'
export type { ParsedEntry } from './parser.js'
export { buildPathIndex, resolveWikilink } from './wikilink-resolver.js'
export { unifiedDiffLines } from './text-diff.js'
