'use client';
/** Exact provider preview and deliberately manual newsletter preparation. [COMP:app-web/feed-linkedin-publishing] */
import {resolveDocFileSrc} from '@/components/doc/doc-file-url';
import {useEffect,useMemo,useState} from 'react';
import {projectFeedLinkedIn,feedCompositionHtml} from '@use-brian/doc-model';
import type {FeedCommand,FeedLinkedInContext} from '@use-brian/shared';
import type {FeedWorkingContent} from '@/lib/offline/feed-offline';
import {useT,useLocale} from '@/lib/i18n/client';
import {Button} from '@/components/ui/button';
import {SearchableSelect} from '@/components/ui/searchable-select';
import {confirmDialog} from '@/components/ui/confirm-dialog';
import {linkedinRequest,linkedinDraftPath,type LinkedInTarget} from '@/lib/api/feed-linkedin';
import {exportFeedSessionArticle} from '@/lib/api/feed';
import {notifyFeedPostsChanged} from '@/lib/feed-posts-events';
export type LinkedInPreviewState={hash:string|null;blocked:boolean};
export function LinkedInPublishing(props:{workspaceId:string;workspaceName:string;assistantId:string;sessionId:string;revision:number;content:FeedWorkingContent;ready:boolean;readOnly?:boolean;disabled:boolean;onCommand:(commands:FeedCommand[])=>Promise<boolean>;onPreview:(state:LinkedInPreviewState)=>void;onPromotion:(url:string)=>Promise<void>;onRefresh:()=>void}){
 const t=useT().feedLinkedIn;const locale=useLocale();
 const editDisabled=props.disabled||props.readOnly;
 const [imageUrls,setImageUrls]=useState<Record<string,string>>({});
 const [deliveries,setDeliveries]=useState<Array<{id:string;revision:number;state:string;createdAt:string;destinationId:string}>>([]);
 const projection=useMemo(()=>props.content.composition?projectFeedLinkedIn(props.content.composition,props.content.linkedin,props.content):null,[props.content]);
 const context:FeedLinkedInContext=props.content.linkedin??{version:1,mode:projection?.mode==='link_post'?'link_post':projection?.mode==='legacy_article'?'newsletter_edition':'post',destinationId:null,authorKind:'person'};
 const [targets,setTargets]=useState<LinkedInTarget[]>([]),[pages,setPages]=useState<Array<{authorUrn:string;displayName:string}>>([]),[error,setError]=useState(''),[receipt,setReceipt]=useState<{url:string;revision:number}|null>(null),[busy,setBusy]=useState(false),[assets,setAssets]=useState<Array<{id:string;name:string}>>([]);
 const path=linkedinDraftPath(props.assistantId,props.sessionId),target=targets.find(d=>d.destinationId===context.destinationId),manual=context.mode==='newsletter_edition';
 const refresh=async()=>{try{const result=await linkedinRequest<{destinations:LinkedInTarget[]}|LinkedInTarget[]>(`distribution/${props.assistantId}/linkedin/destinations`);setTargets((Array.isArray(result)?result:result.destinations).map(d=>({...d,destinationId:d.destinationId??d.id!})));}catch{setTargets([])}};
 useEffect(()=>{void linkedinRequest<{deliveries:typeof deliveries}>(`${path}/linkedin-deliveries`).then(r=>setDeliveries(Array.isArray(r.deliveries)?r.deliveries:[])).catch(()=>{});void refresh();void linkedinRequest<{receipt:{url:string;revision:number}|null}>(`${path}/linkedin-receipt`).then(r=>setReceipt(r.receipt)).catch(()=>{});void linkedinRequest<{sources:Array<{id:string;name:string}>}>(`${path}/sources?kind=file`).then(r=>setAssets(r.sources)).catch(()=>{});},[path]);
 useEffect(()=>{const refreshDelivery=()=>{void linkedinRequest<{deliveries:typeof deliveries}>(`${path}/linkedin-deliveries`).then(r=>setDeliveries(Array.isArray(r.deliveries)?r.deliveries:[])).catch(()=>{});};window.addEventListener('feed:posts-changed',refreshDelivery);window.addEventListener('focus',refreshDelivery);return()=>{window.removeEventListener('feed:posts-changed',refreshDelivery);window.removeEventListener('focus',refreshDelivery);};},[path]);
 useEffect(()=>{const query=new URLSearchParams(window.location.search);if(query.get('linkedin_mode')==='company'&&query.get('linkedin_connection'))void linkedinRequest<{pages:Array<{authorUrn:string;displayName:string}>}>(`distribution/${props.assistantId}/linkedin/destinations`,{connectionId:query.get('linkedin_connection'),authors:[]}).then(r=>setPages(r.pages)).catch(()=>setError(t.failed));},[props.assistantId,t.failed]);
 useEffect(()=>{let live=true;props.onPreview({hash:null,blocked:!!projection?.blockers.length||!!context.destinationId&&!manual&&(!target?.canPublishAs||!target.capabilities?.[context.mode as 'post'|'link_post'])});if(!props.disabled&&target?.canPublishAs&&target.capabilities?.[context.mode as 'post'|'link_post']&&!manual&&context.destinationId&&!projection?.blockers.length){void linkedinRequest<{hash:string}>(`${path}/linkedin-preview?revision=${props.revision}`).then(r=>{if(live)props.onPreview({hash:r.hash,blocked:false});}).catch(()=>{if(live)props.onPreview({hash:null,blocked:true});});}return()=>{live=false};},[path,props.revision,props.disabled,context.destinationId,manual,projection,target]);
 useEffect(()=>{let live=true;void Promise.all([...new Set([...(projection?.media??[]).map(m=>m.fileId),projection?.article?.thumbnailFileId,context.newsletter?.coverFileId].filter((id):id is string=>!!id))].map(async id=>[id,await resolveDocFileSrc(props.workspaceId,id)] as const)).then(rows=>{if(live)setImageUrls(Object.fromEntries(rows));}).catch(()=>{});return()=>{live=false};},[props.workspaceId,projection]);
 const change=(patch:Partial<FeedLinkedInContext>)=>props.onCommand([{kind:'linkedin',metadata:{...context,...patch}}]);
 const newsletter=context.newsletter??{name:'',url:'',editionTitle:props.content.title};
 const field=(key:'name'|'url'|'editionTitle'|'coverCaption'|'launchCommentary',label:string)=><label className="grid gap-1 text-sm" key={`${key}:${props.revision}`}>{label}<input disabled={editDisabled} defaultValue={newsletter[key]??''} onBlur={e=>{if(e.target.value!==(newsletter[key]??''))void change({newsletter:{...newsletter,[key]:e.target.value}});}} className="min-h-11 w-full rounded-md border bg-background px-3 text-base"/></label>;
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();notifyFeedPostsChanged();props.onRefresh();}catch(e){setError(e instanceof Error&&e.message==='delivery_ambiguous'?t.unknownOutcome:t.failed);}finally{setBusy(false);}}
 async function connect(mode:'member'|'company'){if(!await confirmDialog({title:mode==='member'?t.connectPerson:t.connectPage,description:`${props.workspaceName}: ${t.consent}`,confirmLabel:mode==='member'?t.connectPerson:t.connectPage}))return;await action(async()=>{const query=new URLSearchParams({assistantId:props.assistantId,mode,consent:'true',return_to:window.location.origin+window.location.pathname});const result=await linkedinRequest<{redirect:string}>(`linkedin-oauth/authorize?${query}`);window.location.assign(result.redirect);});}
 async function copy(rich:boolean){if(!projection||projection.blockers.length)return;await action(async()=>{if(rich&&navigator.clipboard.write&&props.content.composition){const html=feedCompositionHtml(props.content.composition).replace(/<img\b[^>]*>/g,'');await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([projection.text],{type:'text/plain'})})]);}else await navigator.clipboard.writeText(projection.text);});}
 async function complete(){let url='';if(!await confirmDialog({title:t.markPublished,description:t.manualHelp,confirmLabel:t.markPublished,content:<label>{t.newsletterUrl}<input type="url" onChange={e=>{url=e.target.value;}} className="min-h-11 w-full rounded-md border bg-background px-3"/></label>}))return;await action(async()=>{if(!await props.onCommand([{kind:'release',audience:'public'}]))throw new Error();const confirmed=await linkedinRequest<{confirmationId:string}>(`${path}/confirmation`,{mutationId:crypto.randomUUID(),expectedRevision:props.revision,locale});const result=await linkedinRequest<{receipt:{url:string;revision:number}}>(`${path}/linkedin-published`,{mutationId:crypto.randomUUID(),expectedRevision:props.revision,confirmationId:confirmed.confirmationId,url});setReceipt(result.receipt);});}
 return <section aria-label={t.title} className="space-y-3 rounded-xl border p-3 md:p-4 [&_button]:min-h-11">
  <div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm">{t.mode}<SearchableSelect aria-label={t.mode} value={context.mode} disabled={editDisabled||busy} items={(['post','link_post','newsletter_edition'] as const).map(value=>({value,label:t[value]}))} onValueChange={value=>void change({mode:value as FeedLinkedInContext['mode'],...(value==='newsletter_edition'?{newsletter}: {})})}/></label>
  <label className="grid gap-1 text-sm">{t.author}<SearchableSelect aria-label={t.author} value={context.destinationId??'manual'} disabled={editDisabled||busy} items={[{value:'manual',label:t.manual},...targets.map(d=>({value:d.destinationId,label:d.displayName,hint:d.authorKind==='person'?t.person:t.organization}))]} onValueChange={value=>{const d=targets.find(t=>t.destinationId===value);void change({destinationId:d?.destinationId??null,authorKind:d?.authorKind??context.authorKind,authorDisplay:d?.displayName??context.authorDisplay});}}/></label></div>
  {!context.destinationId?<div className="grid gap-3 md:grid-cols-2"><SearchableSelect aria-label={t.author} value={context.authorKind} disabled={editDisabled} items={[{value:'person',label:t.person},{value:'organization',label:t.organization}]} onValueChange={value=>void change({authorKind:value as 'person'|'organization'})}/><label className="grid gap-1 text-sm">{t.authorDisplay}<input key={props.revision} disabled={editDisabled} defaultValue={context.authorDisplay??''} onBlur={e=>void change({authorDisplay:e.target.value})} className="min-h-11 w-full rounded-md border bg-background px-3"/></label></div>:null}
  <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={props.disabled||busy} onClick={()=>void connect('member')}>{t.connectPerson}</Button><Button variant="outline" disabled={props.disabled||busy} onClick={()=>void connect('company')}>{t.connectPage}</Button>
  {target?.canManageGrant?<Button variant="outline" disabled={busy||props.disabled} onClick={()=>void action(async()=>{if(!await confirmDialog({title:target.workspacePublishing?t.revoke:t.grant,description:`${props.workspaceName}: ${t.consent}`,confirmLabel:target.workspacePublishing?t.revoke:t.grant}))return;await linkedinRequest(`distribution/${props.assistantId}/linkedin/destinations/${target.destinationId}`,{workspacePublishing:!target.workspacePublishing},'PATCH');await refresh();})}>{target.workspacePublishing?t.revoke:t.grant}</Button>:null}
  {target?<Button variant="outline" disabled={busy||props.disabled} onClick={()=>void action(async()=>{if(!await confirmDialog({title:t.disconnect,description:`${props.workspaceName}: ${t.consent}`,confirmLabel:t.disconnect}))return;await linkedinRequest(`distribution/${props.assistantId}/linkedin/destinations/${target.destinationId}`,undefined,'DELETE');await refresh();})}>{t.disconnect}</Button>:null}</div>
  {pages.length?<SearchableSelect aria-label={t.pages} value="" items={pages.map(p=>({value:p.authorUrn,label:p.displayName}))} placeholder={t.selectPage} onValueChange={authorUrn=>void action(async()=>{await linkedinRequest(`distribution/${props.assistantId}/linkedin/destinations`,{connectionId:new URLSearchParams(window.location.search).get('linkedin_connection'),authors:[authorUrn]});await refresh();})}/>:null}
  {target&&!target.canPublishAs?<p role="alert">{t.denied}</p>:null}
  {target&&(target.connectionStatus??target.status)!=='active'?<p role="status">{t.reconnect}</p>:null}
  {target&&!manual&&!target.capabilities?.[context.mode as 'post'|'link_post']?<p role="status">{t.help.inactive}</p>:null}
  {manual?<><div className="grid gap-3 md:grid-cols-2">{field('name',t.newsletterName)}{field('url',t.newsletterUrl)}{field('editionTitle',t.editionTitle)}{field('coverCaption',t.coverCaption)}{field('launchCommentary',t.launchCommentary)}</div><label className="grid gap-1 text-sm">{t.chooseCover}<SearchableSelect aria-label={t.chooseCover} value={newsletter.coverFileId??''} disabled={editDisabled} items={[{value:'',label:t.noCover},...assets.map(a=>({value:a.id,label:a.name}))]} onValueChange={value=>void change({newsletter:{...newsletter,coverFileId:value||null}})}/></label><p className="text-sm text-muted-foreground">{t.manualHelp}</p></>:context.mode==='link_post'?<label className="grid gap-1 text-sm">{t.thumbnail}<SearchableSelect aria-label={t.thumbnail} value={context.thumbnailFileId??''} disabled={editDisabled} items={[{value:'',label:t.noThumbnail},...assets.map(a=>({value:a.id,label:a.name}))]} onValueChange={value=>void change({thumbnailFileId:value||null})}/></label>:null}
  <details open><summary>{t.preview}</summary><p className="text-xs text-muted-foreground">{t.previewHelp}</p><div className="whitespace-pre-wrap break-words py-3 text-sm">{projection?.text}</div>{projection?.media.map((m,i)=><figure key={m.blockId} className="my-2">{imageUrls[m.fileId]?<img className="max-h-64 rounded-md object-contain" src={imageUrls[m.fileId]} alt={m.alt}/>:null}<figcaption className="text-sm">{i+1}. {m.alt}</figcaption></figure>)}{projection?.article?<article className="rounded-md border p-3">{projection.article.thumbnailFileId&&imageUrls[projection.article.thumbnailFileId]?<img className="max-h-64 object-contain" src={imageUrls[projection.article.thumbnailFileId]} alt={projection.article.title}/>:null}<p className="font-medium">{projection.article.title}</p><p>{projection.article.description}</p><p className="break-all text-xs">{projection.article.sourceUrl}</p></article>:null}{projection?.warnings.map((w,i)=><p role="status" key={i}>{w.code==='formatting_loss'?t.formatting_loss:t.inline_attachments}</p>)}{projection?.blockers.length?<div role="alert"><p>{t.blocked}</p>{projection.blockers.map((issue,i)=><p key={i}>{issue.code in t.help?t.help[issue.code as keyof typeof t.help]:t.blocked}</p>)}</div>:null}</details>
  {manual?<div className="flex flex-wrap gap-2"><Button disabled={busy||props.disabled||!!projection?.blockers.length} onClick={()=>void action(async()=>{const blob=await exportFeedSessionArticle(props.assistantId,props.sessionId,props.revision,false);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='linkedin-edition.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>{t.prepare}</Button><Button variant="outline" disabled={busy||props.disabled||!!projection?.blockers.length} onClick={()=>void copy(false)}>{t.copyText}</Button><Button variant="outline" disabled={busy||props.disabled||!!projection?.blockers.length} onClick={()=>void copy(true)}>{t.copyRich}</Button><a className="inline-flex min-h-11 items-center rounded-md border px-3 text-sm" href="https://www.linkedin.com/article/new/" target="_blank" rel="noopener noreferrer">{t.editor}</a><Button variant="outline" disabled={busy||props.disabled||!props.ready||!!projection?.blockers.length||receipt?.revision===props.revision} onClick={()=>void complete()}>{t.markPublished}</Button></div>:null}
  {receipt?<div className="space-y-2"><a href={receipt.url} target="_blank" rel="noopener noreferrer" className="text-sm underline">{t.receipt}</a><Button variant="outline" disabled={busy||props.disabled} onClick={()=>void action(()=>props.onPromotion(receipt.url))}>{t.promotion}</Button></div>:null}
  {deliveries.filter(d=>d.revision===props.revision&&['creating','unknown_outcome'].includes(d.state)).map(d=><div key={d.id} role="status" className="space-y-2 rounded-md border p-3"><p>{t.unknownOutcome}</p><p className="text-sm">{targets.find(target=>target.destinationId===d.destinationId)?.displayName??context.authorDisplay} · {new Date(d.createdAt).toLocaleString()}</p><Button variant="outline" disabled={busy||props.disabled} onClick={()=>void action(async()=>{let url='';if(!await confirmDialog({title:t.markPublished,description:t.unknownOutcome,confirmLabel:t.markPublished,content:<input type="url" aria-label={t.newsletterUrl} onChange={e=>{url=e.target.value;}} className="min-h-11 w-full rounded-md border px-3"/>}))return;await linkedinRequest(`${path}/linkedin-reconcile`,{deliveryId:d.id,expectedRevision:props.revision,url});setDeliveries(rows=>rows.filter(row=>row.id!==d.id));})}>{t.markPublished}</Button></div>)}
  {error?<p role="alert">{error}</p>:null}
 </section>;
}
