/**
 * Regenerate the committed per-turn token-cost snapshot.
 *
 * Usage:
 *   pnpm --filter @use-brian/api token-report
 *
 * Reads the scenarios from `src/routes/_token-cost-scenarios.ts`,
 * runs them, and writes a dated markdown table to
 * `docs/architecture/context-engine/token-cost-snapshot.md`. Commit
 * the updated snapshot alongside whatever change shifted the numbers —
 * same discipline as CHANGELOG.md.
 *
 * The test at `src/routes/__tests__/prompt-token-cost.test.ts`
 * consumes the same scenario list and asserts regression bounds.
 */

import { existsSync } from 'node:fs'
import { writeFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { execFileSync } from 'node:child_process'

import {
  measureAll,
  renderMarkdownTable,
  renderAsciiTable,
  LAYER_1_TOKENS,
  LAYER_1_CHARS,
} from '../src/routes/_token-cost-scenarios.js'

// The api package lives in the open submodule; the context-engine docs live at
// the PLATFORM root. Pre-open-core-split this was a fixed `../../..`, which
// now resolves inside the submodule and mints a stray untracked `docs/` tree
// there. Walk up to the first ancestor that actually carries the
// context-engine docs dir instead; fail loudly in a standalone open clone
// (the snapshot doc is a platform artifact).
function findSnapshotPath(): string {
  let dir = import.meta.dirname
  for (let i = 0; i < 6; i++) {
    const candidate = resolve(dir, 'docs', 'architecture', 'context-engine')
    if (existsSync(candidate)) return resolve(candidate, 'token-cost-snapshot.md')
    dir = resolve(dir, '..')
  }
  throw new Error(
    `token-report: no docs/architecture/context-engine found above ${import.meta.dirname} — run from the platform monorepo checkout`,
  )
}

const SNAPSHOT_PATH = findSnapshotPath()

function tryGit(args: string[]): string {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim()
  } catch {
    return 'unknown'
  }
}

function formatDate(d: Date): string {
  // YYYY-MM-DD in UTC.
  return d.toISOString().slice(0, 10)
}

async function main() {
  const measurements = measureAll()
  const commit = tryGit(['rev-parse', '--short', 'HEAD'])
  const branch = tryGit(['rev-parse', '--abbrev-ref', 'HEAD'])
  const today = formatDate(new Date())

  const body = [
    '# Per-turn input token cost — snapshot',
    '',
    '> This file is regenerated by `pnpm --filter @use-brian/api token-report`. Commit updates alongside the change that shifted the numbers. Live regression guards live in `packages/api/src/routes/__tests__/prompt-token-cost.test.ts`; scenario definitions in `packages/api/src/routes/_token-cost-scenarios.ts`.',
    '',
    `- **Generated:** ${today} (UTC)`,
    `- **Branch:** \`${branch}\``,
    `- **Commit:** \`${commit}\``,
    `- **Layer 1 baseline:** ${LAYER_1_TOKENS} tokens (${LAYER_1_CHARS} chars, cached globally)`,
    '',
    '## Per-scenario totals',
    '',
    renderMarkdownTable(measurements),
    '',
    '## Interpretation notes',
    '',
    '- **Token approximation** is `Math.ceil(chars / 3.5)`. Gemini\'s real tokenizer varies ~10% with content. These numbers are stable proxies, not invoices — production truth lives in `usageMetadata.promptTokenCount`.',
    '- **Tool schemas** use the real factory outputs (`createBaseTools`, `createGoogleCalendarTools`, `createGmailTools`, `createGoogleTasksTools`, `createGitHubTools`, `createNotionTools`, `createMcpSearchTools`) passed through the same Zod → JSON-schema transform the engine applies at runtime.',
    '- **Tool count undercounts production by ~7**: `createBaseTools()` returns only the core-package subset. Scheduling / workers / cache / files / bug-report tools are wired up by the server apps (`apps/api`, `apps/api-admin`) via `buildAllTools()` and aren\'t exercised here. Scenarios are directionally correct; expect ~500–1,000 more tool tokens in production.',
    '- **Power-user row is the target of PR #4** (route built-in connectors through `mcp_search`/`mcp_call`). See `docs/plans/builtin-connectors-tool-search.md`.',
    '',
    '## Plain-text table (same numbers)',
    '',
    '```',
    renderAsciiTable(measurements),
    '```',
    '',
  ].join('\n')

  await mkdir(dirname(SNAPSHOT_PATH), { recursive: true })
  await writeFile(SNAPSHOT_PATH, body, 'utf8')

  process.stdout.write(renderAsciiTable(measurements) + '\n\n')
  process.stdout.write(`Snapshot written: ${SNAPSHOT_PATH}\n`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
