import {createHash} from "node:crypto";
import {beforeEach,describe,it,expect,vi} from "vitest";
const api=vi.hoisted(()=>({fetch:vi.fn()}));
vi.mock("@/lib/auth-fetch",()=>({authFetch:api.fetch}));
import {getCrmErasureReview,getCrmFullPrivacyPolicy,saveCrmFullPrivacyPolicy,previewCrmPrivacy,executeCrmPrivacy,getCrmFileCleanupReceipt,downloadCrmFullPrivacy,type CrmPrivacyPreview} from "@/lib/api/crm-administration";
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
const review:CrmPrivacyPreview={id:"preview-one",previewHash:"a".repeat(64),expiresAt:"2028-01-01T00:00:00Z",policyVersion:4,status:"ready",domains:[],blockers:[],contactId:"contact-one",fileId:"file-one"};
beforeEach(()=>vi.resetAllMocks());
describe("[COMP:app-web/association] Reviewed privacy member contracts",()=>{
  it("reads and saves the complete displayed policy at its observed version",async()=>{const policy={intakeReplay:{retentionSeconds:10},addressSuppression:{retentionSeconds:20},retention:null,importSourceErasure:{receiptRetentionSeconds:30,heldSourceIds:["source-id"]}};api.fetch.mockResolvedValueOnce(response({version:4,policy})).mockResolvedValueOnce(response({}));expect(await getCrmFullPrivacyPolicy("w")).toEqual({version:4,policy});const input={...policy,expectedVersion:4,confirmed:true as const};await saveCrmFullPrivacyPolicy("w",input);expect(JSON.parse(api.fetch.mock.calls[1][1].body)).toEqual(input);api.fetch.mockResolvedValue(response({}));await expect(getCrmFullPrivacyPolicy("w")).rejects.toMatchObject({code:"invalid_response"});});
  it.each([{kind:"erasure",contactId:"contact-one"},{kind:"retention",before:"2026-01-01T00:00:00Z"},{kind:"fileCleanup",fileId:"file-one",before:"2026-01-01T00:00:00Z"}] as const)("previews and executes $kind with the exact server hash, never client-made counts",async input=>{api.fetch.mockResolvedValueOnce(response(review)).mockResolvedValueOnce(response({status:"queued"}));const preview=await previewCrmPrivacy("w",input);await executeCrmPrivacy("w",input,preview);expect(JSON.parse(api.fetch.mock.calls[1][1].body)).toEqual({previewId:review.id,previewHash:review.previewHash,confirmed:true,...(input.kind==="erasure"?{contactId:"contact-one"}:{})});expect(JSON.parse(api.fetch.mock.calls[0][1].body)).not.toHaveProperty("kind");expect(api.fetch.mock.calls[0][0]).toContain(input.kind==="erasure"?"/privacy/erasure-preview":input.kind==="retention"?"/retention/dry-run":"/privacy/file-cleanup-preview");});
  it("refuses mismatched targets, malformed previews and current owner denial",async()=>{api.fetch.mockResolvedValueOnce(response({...review,contactId:"other"}));await expect(previewCrmPrivacy("w",{kind:"erasure",contactId:"contact-one"})).rejects.toMatchObject({code:"invalid_response"});api.fetch.mockResolvedValueOnce(response({...review,previewHash:"wrong"}));await expect(previewCrmPrivacy("w",{kind:"retention",before:"2026-01-01T00:00:00Z"})).rejects.toMatchObject({code:"invalid_response"});api.fetch.mockResolvedValue(response({error:"not_authorized"},403));await expect(executeCrmPrivacy("w",{kind:"erasure",contactId:"contact-one"},review)).rejects.toMatchObject({status:403});});
  it("renews exact erasure reviews and refuses malformed or stale responses",async()=>{
    api.fetch.mockResolvedValueOnce(response({preview:review,receipt:null}));
    expect(await getCrmErasureReview("w",review.id)).toEqual({preview:review,receipt:null});
    expect(api.fetch.mock.calls[0][0]).toContain("/privacy/erasure-previews/"+review.id);expect(api.fetch.mock.calls[0][1]).toBeUndefined();
    api.fetch.mockResolvedValueOnce(response({preview:null,receipt:{previewId:review.id,status:"crm_contact_purged"}}));
    expect((await getCrmErasureReview("w",review.id)).preview).toBeNull();
    api.fetch.mockResolvedValueOnce(response({preview:{...review,id:"another"},receipt:null}));
    await expect(getCrmErasureReview("w",review.id)).rejects.toMatchObject({code:"invalid_response"});
    api.fetch.mockResolvedValueOnce(response({error:"conflict"},409));
    await expect(getCrmErasureReview("w",review.id)).rejects.toMatchObject({name:"SurfaceCacheEvictionError"});
  });
  it("reads the exact asynchronous file-cleanup receipt",async()=>{api.fetch.mockResolvedValue(response({id:"receipt",status:"queued"}));expect(await getCrmFileCleanupReceipt("w","receipt/id")).toEqual({id:"receipt",status:"queued"});expect(api.fetch.mock.calls[0][0]).toContain("/privacy/file-cleanups/receipt%2Fid");expect(api.fetch.mock.calls[0][1]).toBeUndefined();});
});
function exportText(contactId?:string){const records=Array.from({length:103},(_,i)=>`{"type":"record","domain":"crm.contacts","record":{"id":"${i}","amount":9007199254740993}}\n`).join("");const header=JSON.stringify({type:"header",schema:"crm-privacy-v2",workspaceId:"w",scope:contactId?"contact":"workspace",contactId:contactId ?? null,exportId:"export-one"})+"\n";const manifest=JSON.stringify({type:"manifest",schema:"crm-privacy-v2",exportId:"export-one",complete:true,totalRecords:103,sha256:createHash("sha256").update(records).digest("hex"),coverage:[]})+"\n";return {text:header+records+manifest,header,records,manifest};}
describe("[COMP:app-web/association] Verified whole CRM privacy downloads",()=>{
  it("keeps every line beyond 100 records and preserves original numeric precision",async()=>{const fixture=exportText();api.fetch.mockResolvedValue(new Response(fixture.text));const blob=await downloadCrmFullPrivacy("w");expect(await blob.text()).toBe(fixture.text);expect(blob.type).toBe("application/x-ndjson");expect(api.fetch.mock.calls[0][0]).toContain("/operations/privacy-export?format=crm-privacy-v2");});
  it("uses the selected contact endpoint and rejects mismatched subject scope",async()=>{api.fetch.mockResolvedValueOnce(new Response(exportText("contact-one").text));await downloadCrmFullPrivacy("w","contact-one");expect(api.fetch.mock.calls[0][0]).toContain("/contacts/contact-one/privacy-export?format=crm-privacy-v2");api.fetch.mockResolvedValueOnce(new Response(exportText("other").text));await expect(downloadCrmFullPrivacy("w","contact-one")).rejects.toMatchObject({code:"privacy_export_incomplete"});});
  it("rejects a missing committed manifest, missing rows or a changed checksum",async()=>{const fixture=exportText();for(const text of [fixture.header+fixture.records,fixture.text.replace('"totalRecords":103','"totalRecords":104')]){api.fetch.mockResolvedValueOnce(new Response(text));await expect(downloadCrmFullPrivacy("w")).rejects.toMatchObject({code:"privacy_export_incomplete"});}api.fetch.mockResolvedValueOnce(new Response(fixture.text.replace('"id":"0"','"id":"changed"')));await expect(downloadCrmFullPrivacy("w")).rejects.toMatchObject({code:"privacy_export_checksum"});});
  it("never treats an unauthorized response or failed stream as an export",async()=>{api.fetch.mockResolvedValueOnce(response({error:"not_authorized"},403));await expect(downloadCrmFullPrivacy("w")).rejects.toMatchObject({status:403});api.fetch.mockResolvedValueOnce({ok:true,text:async()=>{throw new Error("disconnected");}});await expect(downloadCrmFullPrivacy("w")).rejects.toThrow("disconnected");});
});
