/**
 * Unit tests for the `skill_manage` curator write tool.
 *
 * Verifies:
 *   * Each action validates inputs via Zod
 *   * Routing-by-authorship: auto-generated → direct; user/community → queued
 *   * `create_umbrella` always routes to approvals (regardless of authorship)
 *   * `create_umbrella` runs the class-level naming validator
 *   * Pinned + archived + builtin skills are rejected
 *   * Dangling-pointer validation for patches + new umbrella body
 */

import { describe, it, expect, vi } from 'vitest'
import {
  createSkillManageTool,
  type SkillManageSkill,
  type SkillManageDeps,
  type SkillManageResult,
} from '../manage-tool.js'

function makeAutoGenSkill(over: Partial<SkillManageSkill> = {}): SkillManageSkill {
  return {
    rowId: '11111111-1111-1111-1111-111111111111',
    workspaceId: 'ws-1',
    slug: 'auto-skill',
    name: 'Auto Skill',
    source: 'auto-generated',
    writeOrigin: 'background_review',
    pinned: false,
    state: 'active',
    ...over,
  }
}

function makeUserSkill(over: Partial<SkillManageSkill> = {}): SkillManageSkill {
  return {
    rowId: '22222222-2222-2222-2222-222222222222',
    workspaceId: 'ws-1',
    slug: 'user-skill',
    name: 'User Skill',
    source: 'user',
    writeOrigin: 'foreground',
    pinned: false,
    state: 'active',
    ...over,
  }
}

function makeDeps(over: {
  skill?: SkillManageSkill | null
  files?: Array<{ kind: 'reference' | 'template' | 'script'; name: string; content: string }>
  applyPatch?: ReturnType<typeof vi.fn>
  createAutoGenerated?: ReturnType<typeof vi.fn>
  upsertFile?: ReturnType<typeof vi.fn>
  createStagedSkillUpdate?: ReturnType<typeof vi.fn>
  createStagedSkillCreation?: ReturnType<typeof vi.fn>
} = {}): SkillManageDeps & {
  applyPatch: ReturnType<typeof vi.fn>
  upsertFile: ReturnType<typeof vi.fn>
  createStagedSkillUpdate: ReturnType<typeof vi.fn>
  createStagedSkillCreation: ReturnType<typeof vi.fn>
} {
  const applyPatch = over.applyPatch ?? vi.fn().mockResolvedValue(undefined)
  const createAutoGenerated =
    over.createAutoGenerated ?? vi.fn().mockResolvedValue({ rowId: 'new-row' })
  const upsertFile = over.upsertFile ?? vi.fn().mockResolvedValue(undefined)
  const createStagedSkillUpdate =
    over.createStagedSkillUpdate ?? vi.fn().mockResolvedValue({ approvalId: 'approval-1' })
  const createStagedSkillCreation =
    over.createStagedSkillCreation ?? vi.fn().mockResolvedValue({ approvalId: 'approval-2' })

  return {
    workspaceId: 'ws-1',
    originatingAssistantId: 'asst-1',
    leaseHolderId: 'lease-1',
    systemActorUserId: 'system-1',

    workspaceSkillStore: {
      async getSkillForWorkspace(_ws, _id) {
        return over.skill !== undefined ? over.skill : null
      },
      applyPatch,
      createAutoGenerated,
    },
    fileStore: {
      async list() {
        return over.files ?? []
      },
      upsert: upsertFile,
    },
    approvalsStore: {
      createStagedSkillUpdate,
      createStagedSkillCreation,
    },
    enablementStore: {
      enableForOriginating: vi.fn().mockResolvedValue(undefined),
    },
    applyPatch,
    upsertFile,
    createStagedSkillUpdate,
    createStagedSkillCreation,
  }
}

// Tool context stub — the tool's execute only uses input, but the type
// signature requires the second arg.
const CTX_STUB: never = {
  userId: 'u',
  assistantId: 'a',
  sessionId: 's',
  appId: 'sidanclaw',
  channelType: 'system',
  channelId: 'c',
  workspaceId: 'ws-1',
  abortSignal: new AbortController().signal,
} as unknown as never

function asResult(out: { data: unknown; isError?: boolean }): SkillManageResult {
  return out.data as SkillManageResult
}

describe('[COMP:skills/manage-tool] patch_skill / update_umbrella routing', () => {
  it('rejects when the target skill does not exist', async () => {
    const deps = makeDeps({ skill: null })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: '00000000-0000-0000-0000-000000000000',
        patch: { newContent: 'NEW' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
    expect((out.data as { error: string }).error).toMatch(/not found/i)
  })

  it('rejects when the skill is pinned', async () => {
    const deps = makeDeps({ skill: makeAutoGenSkill({ pinned: true }) })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: makeAutoGenSkill().rowId,
        patch: { newContent: 'NEW' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
    expect((out.data as { error: string }).error).toMatch(/pinned/)
  })

  it('rejects when the skill is archived', async () => {
    const deps = makeDeps({ skill: makeAutoGenSkill({ state: 'archived' }) })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: makeAutoGenSkill().rowId,
        patch: { newContent: 'NEW' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
    expect((out.data as { error: string }).error).toMatch(/archived/)
  })

  it('rejects a builtin skill', async () => {
    const deps = makeDeps({
      skill: makeAutoGenSkill({ source: 'builtin', writeOrigin: 'foreground' }),
    })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: makeAutoGenSkill().rowId,
        patch: { newContent: 'NEW' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
    expect((out.data as { error: string }).error).toMatch(/built-in/i)
  })

  it('routes auto-generated → direct write', async () => {
    const deps = makeDeps({ skill: makeAutoGenSkill() })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: makeAutoGenSkill().rowId,
        patch: { newContent: 'PATCHED BODY' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBeUndefined()
    const result = asResult(out)
    expect((result as { actionTaken: string }).actionTaken).toBe('direct')
    expect(deps.applyPatch).toHaveBeenCalledTimes(1)
    expect(deps.createStagedSkillUpdate).not.toHaveBeenCalled()
  })

  it('routes user-authored → queued_for_approval', async () => {
    const deps = makeDeps({ skill: makeUserSkill() })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: makeUserSkill().rowId,
        patch: { newContent: 'PATCHED BODY' },
      } as never,
      CTX_STUB,
    )
    const result = asResult(out)
    expect((result as { actionTaken: string }).actionTaken).toBe('queued_for_approval')
    expect((result as { approvalId: string }).approvalId).toBe('approval-1')
    expect(deps.createStagedSkillUpdate).toHaveBeenCalledTimes(1)
    expect(deps.applyPatch).not.toHaveBeenCalled()
  })

  it('routes community skill → queued_for_approval', async () => {
    const deps = makeDeps({
      skill: makeUserSkill({ source: 'community', writeOrigin: 'foreground' }),
    })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: makeUserSkill().rowId,
        patch: { newContent: 'PATCHED BODY' },
      } as never,
      CTX_STUB,
    )
    expect((asResult(out) as { actionTaken: string }).actionTaken).toBe('queued_for_approval')
  })

  it('rejects dangling pointers in patch newContent', async () => {
    const deps = makeDeps({
      skill: makeAutoGenSkill(),
      files: [{ kind: 'reference', name: 'have-it', content: 'X' }],
    })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: makeAutoGenSkill().rowId,
        patch: { newContent: 'See {{reference:missing}}.' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
    expect((out.data as { error: string }).error).toMatch(/missing support file/i)
    expect(deps.applyPatch).not.toHaveBeenCalled()
  })

  it('accepts patch newContent whose pointers all resolve', async () => {
    const deps = makeDeps({
      skill: makeAutoGenSkill(),
      files: [{ kind: 'reference', name: 'oauth-flow', content: 'X' }],
    })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: makeAutoGenSkill().rowId,
        patch: { newContent: 'See {{reference:oauth-flow}}.' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBeUndefined()
    expect(deps.applyPatch).toHaveBeenCalledTimes(1)
  })

  it('accepts a diff-only patch (no body, no pointer check)', async () => {
    const deps = makeDeps({ skill: makeAutoGenSkill() })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'patch_skill',
        skillId: makeAutoGenSkill().rowId,
        patch: { diff: '--- a\n+++ b\n@@ ... @@\n+new line' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBeUndefined()
    expect(deps.applyPatch).toHaveBeenCalledTimes(1)
  })

  it('update_umbrella shares patch_skill plumbing (same gates + routing)', async () => {
    const deps = makeDeps({ skill: makeAutoGenSkill() })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'update_umbrella',
        skillId: makeAutoGenSkill().rowId,
        patch: { newContent: 'BROADENED' },
      } as never,
      CTX_STUB,
    )
    expect((asResult(out) as { actionTaken: string }).actionTaken).toBe('direct')
  })

  it('rejects an empty patch (zod refine)', async () => {
    const deps = makeDeps({ skill: makeAutoGenSkill() })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      { action: 'patch_skill', skillId: makeAutoGenSkill().rowId, patch: {} } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
  })
})

describe('[COMP:skills/manage-tool] add_support_file routing', () => {
  it('rejects when the skill does not exist', async () => {
    const deps = makeDeps({ skill: null })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'add_support_file',
        skillId: '00000000-0000-0000-0000-000000000000',
        file: { kind: 'reference', name: 'note', content: 'X' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
  })

  it('routes auto-generated → direct upsert', async () => {
    const deps = makeDeps({ skill: makeAutoGenSkill() })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'add_support_file',
        skillId: makeAutoGenSkill().rowId,
        file: { kind: 'reference', name: 'note', content: 'CONTENT' },
      } as never,
      CTX_STUB,
    )
    expect((asResult(out) as { actionTaken: string }).actionTaken).toBe('direct')
    expect(deps.upsertFile).toHaveBeenCalledTimes(1)
    expect(deps.createStagedSkillUpdate).not.toHaveBeenCalled()
  })

  it('routes user-authored → queued_for_approval with addedFiles payload', async () => {
    const deps = makeDeps({ skill: makeUserSkill() })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'add_support_file',
        skillId: makeUserSkill().rowId,
        file: { kind: 'template', name: 'starter.md', content: 'X' },
      } as never,
      CTX_STUB,
    )
    expect((asResult(out) as { actionTaken: string }).actionTaken).toBe('queued_for_approval')
    expect(deps.createStagedSkillUpdate).toHaveBeenCalledTimes(1)
    const call = deps.createStagedSkillUpdate.mock.calls[0][0]
    expect(call.proposedPatch.addedFiles).toHaveLength(1)
    expect(call.proposedPatch.addedFiles[0].kind).toBe('template')
  })

  it('rejects a file body whose pointers refer to non-existent siblings', async () => {
    const deps = makeDeps({
      skill: makeAutoGenSkill(),
      files: [{ kind: 'reference', name: 'have-it', content: 'X' }],
    })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'add_support_file',
        skillId: makeAutoGenSkill().rowId,
        file: {
          kind: 'reference',
          name: 'new-one',
          content: 'See {{reference:missing}}.',
        },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
    expect((out.data as { error: string }).error).toMatch(/missing support file/i)
  })

  it('accepts a self-referential file body (file refers to itself)', async () => {
    const deps = makeDeps({
      skill: makeAutoGenSkill(),
      files: [],
    })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'add_support_file',
        skillId: makeAutoGenSkill().rowId,
        file: {
          kind: 'reference',
          name: 'self-ref',
          content: 'See {{reference:self-ref}} (recursive note).',
        },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBeUndefined()
  })

  it('rejects a file name containing curly braces', async () => {
    const deps = makeDeps({ skill: makeAutoGenSkill() })
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'add_support_file',
        skillId: makeAutoGenSkill().rowId,
        file: { kind: 'reference', name: 'bad{name}', content: 'X' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
  })
})

describe('[COMP:skills/manage-tool] create_umbrella routing', () => {
  it('rejects a session-artifact name with the validator reason', async () => {
    const deps = makeDeps()
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'create_umbrella',
        umbrella: {
          name: 'fix-stripe-webhook',
          description: 'desc',
          content: 'body',
        },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
    expect((out.data as { error: string }).error).toMatch(/Umbrella name rejected/)
    expect(deps.createStagedSkillCreation).not.toHaveBeenCalled()
  })

  it('rejects a body whose pointers refer to support files not in the proposal', async () => {
    const deps = makeDeps()
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'create_umbrella',
        umbrella: {
          name: 'customer-onboarding',
          description: 'desc',
          content: 'See {{reference:nope}}.',
          // No supportFiles provided.
        },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
    expect((out.data as { error: string }).error).toMatch(/not in the proposal/i)
  })

  it('accepts a body whose pointers all resolve to proposed support files', async () => {
    const deps = makeDeps()
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'create_umbrella',
        umbrella: {
          name: 'customer-onboarding',
          description: 'desc',
          content: 'See {{reference:flow}}.',
          supportFiles: [{ kind: 'reference', name: 'flow', content: 'FLOW' }],
        },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBeUndefined()
    expect((asResult(out) as { actionTaken: string }).actionTaken).toBe('queued_for_approval')
    expect(deps.createStagedSkillCreation).toHaveBeenCalledTimes(1)
  })

  it('always routes through approvals — never direct, even for trusted curator', async () => {
    const deps = makeDeps()
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'create_umbrella',
        umbrella: {
          name: 'customer-onboarding',
          description: 'desc',
          content: 'plain body',
        },
      } as never,
      CTX_STUB,
    )
    expect((asResult(out) as { actionTaken: string }).actionTaken).toBe('queued_for_approval')
  })

  it('rejects an empty umbrella name (zod min(1))', async () => {
    const deps = makeDeps()
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'create_umbrella',
        umbrella: { name: '', description: 'desc', content: 'body' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
  })

  it('rejects an umbrella with no alphanumeric chars in its name', async () => {
    const deps = makeDeps()
    const tool = createSkillManageTool(deps)
    const out = await tool.execute(
      {
        action: 'create_umbrella',
        umbrella: { name: '!!!', description: 'desc', content: 'body' },
      } as never,
      CTX_STUB,
    )
    expect(out.isError).toBe(true)
  })
})
