/**
 * Unit tests for the V2 skill-review worker (WS-B).
 *
 * The worker has three failure-isolation surfaces:
 *   * Per-workspace rate cap — skip cycle + log + still mark reviewed
 *   * Per-skill review lease — first-writer-wins
 *   * Per-action failure — isolated; cycle continues
 *
 * These tests target the per-session `reviewSession` entry point with
 * faked stores so the cycle can be exercised in-memory. The
 * `countTodayOps` helper hits the real `query` import, so the rate-cap
 * branch is exercised via `dailyOpCap: 0` (which forces the cap check to
 * trip even when there are no analytics events).
 *
 * Spec: `docs/architecture/engine/skill-system.md` → "Failure modes" +
 * "Per-workspace rate cap" + "Concurrent-review lease".
 */

import { describe, it, expect, vi, beforeEach } from 'vitest'
import { reviewSession, selectCandidateSessions, type SkillReviewLLM } from '../skill-review-worker.js'
import { query } from '../../db/client.js'
import { createSkillManageTool } from '@use-brian/core'

// We mock the `query` import so the worker's analytics + session-touch DB
// calls don't hit a real DB. Vitest's auto-mock keeps the API simple.
vi.mock('../../db/client.js', () => ({
  query: vi.fn(async () => ({ rows: [{ count: '0' }], rowCount: 0 })),
}))

// `createSkillManageTool` from @use-brian/core is the action dispatch path.
// We mock the entire core module so the worker's lazy import returns a
// tool whose execute method delegates to our fakes.
vi.mock('@use-brian/core', async (importOriginal) => {
  const orig = await importOriginal<typeof import('@use-brian/core')>()
  return {
    ...orig,
    createSkillManageTool: vi.fn(() => ({
      name: 'skill_manage',
      description: 'mocked',
      inputSchema: orig.createSkillManageTool({
        workspaceId: 'x',
        originatingAssistantId: null,
        leaseHolderId: 'l',
        systemActorUserId: 'u',
        workspaceSkillStore: {
          async getSkillForWorkspace() { return null },
          async applyPatch() {},
          async createAutoGenerated() { return { rowId: 'x' } },
        },
        fileStore: { async list() { return [] }, async upsert() {} },
        approvalsStore: {
          async createStagedSkillUpdate() { return { approvalId: 'a' } },
          async createStagedSkillCreation() { return { approvalId: 'a' } },
          async findPendingStagedSkillUpdate() { return null },
          async findPendingStagedSkillCreation() { return null },
        },
        enablementStore: { async enableForOriginating() {} },
      }).inputSchema,
      isConcurrencySafe: false,
      isReadOnly: false,
      requiresConfirmation: false,
      execute: vi.fn(async () => ({ data: { actionTaken: 'direct', targetSkillId: 'mock-skill' } })),
    })),
  }
})

function makeAnalyticsStore() {
  const recorded: Array<{ eventName: string; metadata: Record<string, unknown> }> = []
  return {
    recorded,
    record: vi.fn(async (event: { eventName: string; metadata: Record<string, unknown> }) => {
      recorded.push({ eventName: event.eventName, metadata: event.metadata })
    }),
    recordBatch: vi.fn(),
    getDailyReport: vi.fn(),
    getWeeklyReport: vi.fn(),
    listErrors: vi.fn(),
    summarizeErrors: vi.fn(),
    pruneOldEvents: vi.fn(),
  }
}

function makeWorkspaceSkillStore(opts?: {
  acquireLease?: (skillId: string) => boolean
  skills?: Array<{ rowId: string; name: string; description: string; content: string; state: string }>
}) {
  const acquireCalls: string[] = []
  const releaseCalls: string[] = []
  return {
    acquireCalls,
    releaseCalls,
    listForWorkspace: vi.fn(async () =>
      (opts?.skills ?? []).map((s) => ({
        rowId: s.rowId,
        id: s.rowId,
        workspaceId: 'ws-1',
        slug: s.rowId,
        name: s.name,
        description: s.description,
        content: s.content,
        category: 'custom',
        requiresConnectors: [],
        source: 'auto-generated' as const,
        published: false,
        writeOrigin: 'background_review' as const,
        state: s.state as 'active' | 'stale' | 'archived',
        stateTransitionedAt: new Date(),
        pinned: false,
        invocations: 0,
        succeeded: 0,
        userCorrectedAfter: 0,
        validFrom: new Date(),
      })),
    ),
    acquireReviewLease: vi.fn(async (id: string) => {
      acquireCalls.push(id)
      return opts?.acquireLease ? opts.acquireLease(id) : true
    }),
    releaseReviewLease: vi.fn(async (id: string) => {
      releaseCalls.push(id)
    }),
    // Unused methods — left as undefined casts so TS is happy.
  } as unknown as import('../../db/skill-store.js').WorkspaceSkillStore & {
    acquireCalls: string[]
    releaseCalls: string[]
  }
}

function makeMinimalDeps() {
  return {
    fileStore: { async list() { return [] }, async upsert() {} } as unknown as import('../../db/workspace-skill-files-store.js').WorkspaceSkillFilesStore,
    approvalsStore: {
      async createStagedSkillUpdate() { return { id: 'a' } },
      async createStagedSkillCreation() { return { id: 'a' } },
    } as unknown as import('../../db/pending-approvals-store.js').PendingApprovalsStore,
  }
}

function makeLLM(actions: Parameters<SkillReviewLLM['plan']>[0] extends infer _ ? never : never): never
function makeLLM(plan: Awaited<ReturnType<SkillReviewLLM['plan']>>): SkillReviewLLM
function makeLLM(plan: Awaited<ReturnType<SkillReviewLLM['plan']>>): SkillReviewLLM {
  return {
    plan: vi.fn(async () => plan),
  }
}

beforeEach(() => {
  vi.clearAllMocks()
})

const CANDIDATE = {
  sessionId: '00000000-0000-0000-0000-0000000000a1',
  workspaceId: '00000000-0000-0000-0000-0000000000a2',
  assistantId: '00000000-0000-0000-0000-0000000000a3',
  userId: '00000000-0000-0000-0000-0000000000a4',
  currentTurnCount: 10,
  lastReviewedTurn: null,
}

describe('[COMP:workers/skill-review-worker] reviewSession', () => {
  it("returns 'skipped' and logs `skill_review_rate_capped` when at cap", async () => {
    const analytics = makeAnalyticsStore()
    const workspaceSkillStore = makeWorkspaceSkillStore()
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm = makeLLM({ actions: [] })

    const outcome = await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 0, // forces cap to trip
      now: () => new Date(),
    })
    expect(outcome).toBe('skipped')
    expect(analytics.recorded.map((e) => e.eventName)).toContain('skill_review_rate_capped')
    // The LLM was NOT called because we short-circuit before the plan call.
    expect(llm.plan).not.toHaveBeenCalled()
  })

  it("returns 'reviewed' with no actions when the LLM emits an empty plan", async () => {
    const analytics = makeAnalyticsStore()
    const workspaceSkillStore = makeWorkspaceSkillStore({ skills: [] })
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm = makeLLM({ actions: [] })

    const outcome = await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 10,
      now: () => new Date(),
    })
    expect(outcome).toBe('reviewed')
    // No lease acquisitions because no targets.
    expect(workspaceSkillStore.acquireCalls).toHaveLength(0)
  })

  it('acquires a lease per target skill and releases on completion', async () => {
    const analytics = makeAnalyticsStore()
    const skillId = '00000000-0000-0000-0000-0000000000b1'
    const workspaceSkillStore = makeWorkspaceSkillStore({
      skills: [{ rowId: skillId, name: 'X', description: 'd', content: 'c', state: 'active' }],
    })
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm = makeLLM({
      actions: [
        { action: 'patch_skill', skillId, patch: { newContent: 'PATCH' } },
      ],
    })

    await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 10,
      now: () => new Date(),
    })
    expect(workspaceSkillStore.acquireCalls).toEqual([skillId])
    expect(workspaceSkillStore.releaseCalls).toEqual([skillId])
  })

  it('logs `skill_review_skipped_concurrent` when lease acquisition fails', async () => {
    const analytics = makeAnalyticsStore()
    const skillId = '00000000-0000-0000-0000-0000000000c1'
    const workspaceSkillStore = makeWorkspaceSkillStore({
      acquireLease: () => false, // every attempt fails
      skills: [{ rowId: skillId, name: 'X', description: 'd', content: 'c', state: 'active' }],
    })
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm = makeLLM({
      actions: [
        { action: 'patch_skill', skillId, patch: { newContent: 'PATCH' } },
      ],
    })

    await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 10,
      now: () => new Date(),
    })
    expect(analytics.recorded.map((e) => e.eventName)).toContain('skill_review_skipped_concurrent')
    // No release because nothing was acquired.
    expect(workspaceSkillStore.releaseCalls).toHaveLength(0)
  })

  it('logs `skill_review_cycle_failed` when the LLM plan call throws', async () => {
    const analytics = makeAnalyticsStore()
    const workspaceSkillStore = makeWorkspaceSkillStore({ skills: [] })
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm: SkillReviewLLM = {
      plan: vi.fn(async () => {
        throw new Error('LLM exploded')
      }),
    }

    const outcome = await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 10,
      now: () => new Date(),
    })
    expect(outcome).toBe('failed')
    expect(analytics.recorded.map((e) => e.eventName)).toContain('skill_review_cycle_failed')
  })

  it('emits `session_reviewed` events when the cycle succeeds', async () => {
    const analytics = makeAnalyticsStore()
    const workspaceSkillStore = makeWorkspaceSkillStore({ skills: [] })
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm = makeLLM({ actions: [] })

    const events: string[] = []
    await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 10,
      now: () => new Date(),
      onEvent: (e) => events.push(e.type),
    })
    expect(events).toContain('session_reviewed')
  })

  it('drops actions whose target failed to lease (filtered before apply)', async () => {
    const analytics = makeAnalyticsStore()
    const leasedSkill = '00000000-0000-0000-0000-0000000000d1'
    const unleasedSkill = '00000000-0000-0000-0000-0000000000d2'
    const workspaceSkillStore = makeWorkspaceSkillStore({
      acquireLease: (id) => id === leasedSkill,
      skills: [
        { rowId: leasedSkill, name: 'L', description: 'd', content: 'c', state: 'active' },
        { rowId: unleasedSkill, name: 'U', description: 'd', content: 'c', state: 'active' },
      ],
    })
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm = makeLLM({
      actions: [
        { action: 'patch_skill', skillId: leasedSkill, patch: { newContent: 'A' } },
        { action: 'patch_skill', skillId: unleasedSkill, patch: { newContent: 'B' } },
      ],
    })

    await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 10,
      now: () => new Date(),
    })
    // The unleased skill produces a `skill_review_skipped_concurrent`; the
    // leased one produces a `skill_review_action_succeeded`.
    const names = analytics.recorded.map((e) => e.eventName)
    expect(names).toContain('skill_review_skipped_concurrent')
    expect(names).toContain('skill_review_action_succeeded')
    // Only the leased target appears in the release log.
    expect(workspaceSkillStore.releaseCalls).toEqual([leasedSkill])
  })

  it('drops an action targeting a skillId not in this workspace (tenant-safety)', async () => {
    const analytics = makeAnalyticsStore()
    const ownSkill = '00000000-0000-0000-0000-0000000000f1'
    // A valid UUID that is NOT among the workspace's skills (a hallucination,
    // or a foreign tenant's row). It must never reach `acquireReviewLease`.
    const foreignSkill = '00000000-0000-0000-0000-0000000000f2'
    const workspaceSkillStore = makeWorkspaceSkillStore({
      skills: [{ rowId: ownSkill, name: 'O', description: 'd', content: 'c', state: 'active' }],
    })
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm = makeLLM({
      actions: [{ action: 'patch_skill', skillId: foreignSkill, patch: { newContent: 'X' } }],
    })

    const outcome = await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 10,
      now: () => new Date(),
    })
    // No lease is ever attempted on the foreign id — it's filtered before the
    // lease loop, so it can't stamp a lease on another workspace's row.
    expect(workspaceSkillStore.acquireCalls).toHaveLength(0)
    expect(analytics.recorded.map((e) => e.eventName)).not.toContain('skill_review_action_succeeded')
    // The cycle is clean (no applied action, no failure).
    expect(outcome).toBe('reviewed')
  })

  it('logs `skill_review_action_deduped` and spends no cap when the tool skips a duplicate proposal', async () => {
    const analytics = makeAnalyticsStore()
    const skillId = '00000000-0000-0000-0000-0000000000d9'
    const workspaceSkillStore = makeWorkspaceSkillStore({
      skills: [{ rowId: skillId, name: 'X', description: 'd', content: 'c', state: 'active' }],
    })
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm = makeLLM({
      actions: [{ action: 'patch_skill', skillId, patch: { newContent: 'AGAIN' } }],
    })

    // The tool reports the dedupe skip for this cycle's single action.
    vi.mocked(createSkillManageTool).mockReturnValueOnce({
      name: 'skill_manage',
      description: 'mocked',
      inputSchema: undefined,
      isConcurrencySafe: false,
      isReadOnly: false,
      requiresConfirmation: false,
      execute: vi.fn(async () => ({
        data: {
          actionTaken: 'skipped_pending_approval',
          targetSkillId: skillId,
          approvalId: 'existing-1',
        },
      })),
    } as never)

    const events: string[] = []
    const outcome = await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 10,
      now: () => new Date(),
      onEvent: (e) => events.push(e.type),
    })

    const names = analytics.recorded.map((e) => e.eventName)
    expect(names).toContain('skill_review_action_deduped')
    // A dedupe skip is neither an op (no cap spend) nor a failure.
    expect(names).not.toContain('skill_review_action_succeeded')
    expect(names).not.toContain('skill_review_action_failed')
    expect(events).toContain('action_deduped')
    expect(outcome).toBe('reviewed')
    // The lease is still released.
    expect(workspaceSkillStore.releaseCalls).toEqual([skillId])
  })

  it('honors mid-cycle cap — stops applying further actions once cap is reached', async () => {
    const analytics = makeAnalyticsStore()
    const a = '00000000-0000-0000-0000-0000000000e1'
    const b = '00000000-0000-0000-0000-0000000000e2'
    const workspaceSkillStore = makeWorkspaceSkillStore({
      skills: [
        { rowId: a, name: 'A', description: 'd', content: 'c', state: 'active' },
        { rowId: b, name: 'B', description: 'd', content: 'c', state: 'active' },
      ],
    })
    const { fileStore, approvalsStore } = makeMinimalDeps()
    const llm = makeLLM({
      actions: [
        { action: 'patch_skill', skillId: a, patch: { newContent: 'A' } },
        { action: 'patch_skill', skillId: b, patch: { newContent: 'B' } },
      ],
    })

    await reviewSession(CANDIDATE, {
      workspaceSkillStore,
      fileStore,
      approvalsStore,
      analyticsStore: analytics as unknown as import('@use-brian/core').AnalyticsStore,
      reviewLLM: llm,
      leaseHolderId: 'lease-1',
      leaseMinutes: 5,
      dailyOpCap: 1, // only one op allowed
      now: () => new Date(),
    })
    const ops = analytics.recorded.filter((e) => e.eventName === 'skill_review_action_succeeded')
    expect(ops.length).toBe(1)
    expect(analytics.recorded.map((e) => e.eventName)).toContain('skill_review_rate_capped')
  })
})

describe('[COMP:workers/skill-review-worker] selectCandidateSessions', () => {
  it('resolves the workspace through the assistant so chat sessions (NULL sessions.workspace_id) qualify', async () => {
    const mockedQuery = vi.mocked(query)
    mockedQuery.mockResolvedValueOnce({
      rows: [
        {
          session_id: '00000000-0000-0000-0000-0000000000b1',
          workspace_id: '00000000-0000-0000-0000-0000000000b2',
          assistant_id: '00000000-0000-0000-0000-0000000000b3',
          user_id: '00000000-0000-0000-0000-0000000000b4',
          current_turn_count: '12',
          last_skill_reviewed_turn: null,
        },
      ],
      rowCount: 1,
    } as never)

    const candidates = await selectCandidateSessions(10, 24)

    expect(candidates).toEqual([
      {
        sessionId: '00000000-0000-0000-0000-0000000000b1',
        workspaceId: '00000000-0000-0000-0000-0000000000b2',
        assistantId: '00000000-0000-0000-0000-0000000000b3',
        userId: '00000000-0000-0000-0000-0000000000b4',
        currentTurnCount: 12,
        lastReviewedTurn: null,
      },
    ])

    // Regression (2026-07-07): `sessions.workspace_id` is written only for
    // workspace-visible artifact sessions (doc/canvas threads — it backs the
    // RLS gate; see `db/sessions.ts`), so ordinary chat sessions carry NULL.
    // Filtering on the session column alone excluded every chat session and
    // the worker never found a candidate. The SQL must resolve the workspace
    // through the assistants join.
    const sql = mockedQuery.mock.calls[0]![0] as string
    expect(sql).toContain('COALESCE(s.workspace_id, a.workspace_id)')
    expect(sql).not.toMatch(/AND s\.workspace_id IS NOT NULL/)
  })
})
