/**
 * S10 skill consolidation — umbrella pass.
 *
 * Detects clusters of narrow auto-generated skills that should belong
 * together under a class-level umbrella. Patches the umbrella in place,
 * archives absorbed members with mandatory `absorbed_into` metadata.
 *
 * Cadence: new REM emission target — runs in the existing weekly cycle.
 * No new worker. Wire-in is in `phases.ts` (`runREMSkillUmbrella`).
 *
 * Trigger gate: workspace has >= 20 `auto-generated`, non-pinned,
 * non-archived skills AND workspace_age >= 21 days. Below either
 * threshold: skip.
 *
 * Curator semantics:
 *  - archive-only, never auto-delete
 *  - `absorbed_into` mandatory (drives in-flight reference migration)
 *  - pinned exempt
 *  - `write_origin = 'foreground'` exempt (user-authored skills never
 *    auto-curated)
 *  - 30-day undo window before hard-delete (handled by the WS-A store)
 *
 * Spec: `docs/architecture/context-engine/memory-consolidation.md` §"Skill consolidation
 * — umbrella pass (S10 lock)".
 *
 * [COMP:consolidation/skill-umbrella]
 */

import { z } from 'zod'

// ── Workspace skill shape — slice of WS-A's WorkspaceSkill ───────
//
// Mirrors `packages/api/src/db/skill-store.ts` `WorkspaceSkill` for the
// columns the curator actually reads. Re-stating the shape here keeps
// `@sidanclaw/core` decoupled from `@sidanclaw/api` (matches the same
// dependency boundary every other store-shaped consumer in core uses).

export type UmbrellaSkill = {
  /** Row UUID — used for absorbed_into, lease handles, etc. */
  rowId: string
  /** Slug — stable cross-workspace identifier. */
  id: string
  workspaceId: string
  slug: string
  name: string
  description: string
  whenToUse?: string
  content: string
  category: string
  requiresConnectors: string[]
  source: 'builtin' | 'user' | 'community' | 'auto-generated'
  authorId?: string
  published: boolean
  writeOrigin: 'foreground' | 'background_review'
  state: 'active' | 'stale' | 'archived'
  stateTransitionedAt: Date
  lastInvokedAt?: Date
  pinned: boolean
  pinnedAt?: Date
  originatingAssistantId?: string
  autoGeneratedAt?: Date
  acknowledgedAt?: Date
  absorbedInto?: string
  absorbedAt?: Date
  lastPatchDiff?: string
  lastPatchDiffAt?: Date
  invocations: number
  succeeded: number
  userCorrectedAfter: number
  validFrom: Date
  validTo?: Date
}

// ── Store contracts (READ-ONLY adapters over WS-A) ───────────────

/**
 * Slice of WS-A's `WorkspaceSkillStore` consumed by the umbrella pass.
 * The pass treats the store as an opaque adapter so per-row commits can
 * be wrapped in a single transaction at the wiring site
 * (`apps/api/src/index.ts`). The WS-A store implements each method
 * already; the wiring layer composes them.
 */
export type SkillUmbrellaStore = {
  /** Curator candidate set, already filtered by background_review-origin,
   *  non-pinned, in ('active','stale'), valid_to IS NULL. */
  listCuratorEligible(workspaceId: string): Promise<UmbrellaSkill[]>

  /** Apply a `MERGE_INTO_EXISTING` move: patch the target's content and
   *  record the diff for the 30-day undo window. */
  patchUmbrella(skillId: string, patch: {
    content: string
    diff: string
  }): Promise<void>

  /** Apply a `CREATE_NEW_UMBRELLA` move: insert a new auto-generated
   *  skill row under the originating assistant. Returns the new row UUID
   *  so absorbed members can record `absorbed_into = <newId>`. */
  createUmbrella(workspaceId: string, draft: {
    slug: string
    name: string
    description: string
    whenToUse?: string
    content: string
    category?: string
    requiresConnectors?: string[]
    originatingAssistantId?: string | null
  }): Promise<{ rowId: string }>

  /** Apply a `DEMOTE_TO_REFERENCES` move: insert a support file under
   *  the umbrella. Mirrors `workspace_skill_files` `upsert`. */
  addSupportFile(params: {
    umbrellaRowId: string
    kind: 'reference' | 'template' | 'script'
    name: string
    content: string
    description?: string | null
  }): Promise<void>

  /** Archive an absorbed member with mandatory `absorbed_into` metadata.
   *  Sets `state = 'archived'`, `absorbed_into = <umbrellaRowId>`,
   *  `absorbed_at = now()`. */
  recordAbsorption(memberRowId: string, umbrellaRowId: string): Promise<void>
}

/**
 * Slice of WS-A's `SkillCuratorDigestStore` consumed by the umbrella
 * pass. Used for both the weekly transparency surface AND the
 * per-cluster re-extraction protection (a cluster the user un-did stays
 * un-proposed for 30 days).
 */
export type SkillUmbrellaDigestStore = {
  append(workspaceId: string, weekOf: Date, actions: SkillCuratorAction[]): Promise<unknown>
  /** Recent digests (newest first) — used to read the re-extraction
   *  protection list. */
  listForWorkspace(workspaceId: string, limit?: number): Promise<Array<{
    weekOf: Date
    actions: unknown
  }>>
}

// ── Action shape persisted on `skill_curator_digest.actions` ─────

export type SkillCuratorAction =
  | {
      kind: 'merged_into_existing'
      umbrellaRowId: string
      absorbedMemberRowIds: string[]
      rationale: string
      undone?: boolean
      undoneAt?: Date
    }
  | {
      kind: 'created_new_umbrella'
      umbrellaRowId: string
      absorbedMemberRowIds: string[]
      rationale: string
      undone?: boolean
      undoneAt?: Date
    }
  | {
      kind: 'demoted_to_references'
      umbrellaRowId: string
      absorbedMemberRowIds: string[]
      rationale: string
      undone?: boolean
      undoneAt?: Date
    }
  | {
      kind: 'skipped'
      reason:
        | 'no_embeddings'
        | 'cluster_proposal_rejected'
        | 'commit_failed'
        | 'recent_undo'
        | 'malformed_llm_output'
      memberRowIds: string[]
      detail?: string
    }

// ── Event hook ───────────────────────────────────────────────────

export type SkillUmbrellaEvent =
  | {
      type: 'skill_umbrella_skipped'
      workspaceId: string
      reason:
        | 'insufficient_skills'
        | 'workspace_too_young'
        | 'no_embeddings'
        | 'no_clusters'
    }
  | {
      type: 'skill_umbrella_cluster_committed'
      workspaceId: string
      action: SkillCuratorAction
    }
  | {
      type: 'skill_umbrella_cluster_failed'
      workspaceId: string
      reason: string
      memberRowIds: string[]
    }

// ── Trigger gates ────────────────────────────────────────────────

const MIN_SKILL_COUNT_DEFAULT = 20
const MIN_WORKSPACE_AGE_DAYS_DEFAULT = 21
const SKILL_UPDATED_AT_GRACE_DAYS_DEFAULT = 7
const CLUSTER_THRESHOLD_DEFAULT = 0.65
const MAX_CLUSTERS_PER_RUN_DEFAULT = 3
const RE_EXTRACTION_PROTECTION_DAYS_DEFAULT = 30
const DIGEST_LOOKBACK_WEEKS = 8
const MIN_CLUSTER_SIZE = 2

// ── Prompt (PROCEDURAL_UMBRELLA_PROMPT) ──────────────────────────
//
// Uses umbrella-class framing, a three-move taxonomy, and explicit
// anti-patterns. JSON output for clean Zod parsing.

const PROCEDURAL_UMBRELLA_PROMPT = `You are the skill curator. A cluster of narrow auto-generated skills was detected. Decide one of three moves:

1. MERGE_INTO_EXISTING — one cluster member is broad enough to be the umbrella; patch it with absorbed subsections.
2. CREATE_NEW_UMBRELLA — no member is broad enough; draft a fresh class-level umbrella.
3. DEMOTE_TO_REFERENCES — move narrow content into the umbrella's references/templates/scripts.

UMBRELLA CLASS FRAMING:
A class-level umbrella names a CATEGORY of task (e.g. "customer-onboarding", "weekly-reporting", "incident-triage"), not a specific instance. Its content describes WHEN to use it and the canonical procedure, with absorbed details as subsections, pitfalls, or trigger conditions.

ANTI-PATTERNS — reject and skip when:
- Session-artifact names: fix-*, debug-*, audit-*, today-*, dated, PR-numbered, specific error strings
- Environment-dependent failures ("command not found", "wrong directory")
- Negative tool claims ("X is broken")
- One-off task narratives

CLUSTER MEMBERS (each row: rowId | slug | name | description):
{{MEMBERS}}

Constraints:
- Output ONLY a single JSON object, no preamble, no fences.
- absorbed_member_ids MUST be a subset of the cluster member rowIds and MUST include at least one member.
- For MERGE_INTO_EXISTING: target_skill_id MUST be one of the cluster member rowIds (the broadest one).
- For DEMOTE_TO_REFERENCES: umbrella_skill_id MUST be one of the cluster member rowIds.

Output JSON shape (one of):

MERGE_INTO_EXISTING:
{
  "move": "MERGE_INTO_EXISTING",
  "target_skill_id": "<rowId>",
  "patched_content": "<full new SKILL.md body for the umbrella>",
  "absorbed_member_ids": ["<rowId>", ...],
  "rationale": "<one-sentence human-readable explanation>"
}

CREATE_NEW_UMBRELLA:
{
  "move": "CREATE_NEW_UMBRELLA",
  "new_skill_draft": {
    "slug": "<kebab-case-class-name>",
    "name": "<Title Case Class Name>",
    "description": "<one-line whenToUse>",
    "when_to_use": "<one-line trigger conditions>",
    "content": "<full SKILL.md body>",
    "category": "custom"
  },
  "absorbed_member_ids": ["<rowId>", ...],
  "rationale": "<one-sentence human-readable explanation>"
}

DEMOTE_TO_REFERENCES:
{
  "move": "DEMOTE_TO_REFERENCES",
  "umbrella_skill_id": "<rowId>",
  "demote_map": [
    {"member_id": "<rowId>", "target_kind": "reference|template|script", "target_name": "<filename>"}
  ],
  "absorbed_member_ids": ["<rowId>", ...],
  "rationale": "<one-sentence human-readable explanation>"
}

If the cluster does not justify any move (anti-patterns dominate, members are unrelated, etc.), output exactly:
{"move":"REJECT","reason":"<one-sentence>"}`

// ── Zod schemas for parsing the proposal ─────────────────────────

const MergeIntoExistingSchema = z.object({
  move: z.literal('MERGE_INTO_EXISTING'),
  target_skill_id: z.string().min(1),
  patched_content: z.string().min(1),
  absorbed_member_ids: z.array(z.string().min(1)).min(1),
  rationale: z.string().min(1),
})

const CreateNewUmbrellaSchema = z.object({
  move: z.literal('CREATE_NEW_UMBRELLA'),
  new_skill_draft: z.object({
    slug: z.string().min(1),
    name: z.string().min(1),
    description: z.string().min(1),
    when_to_use: z.string().optional(),
    content: z.string().min(1),
    category: z.string().optional(),
    requires_connectors: z.array(z.string()).optional(),
  }),
  absorbed_member_ids: z.array(z.string().min(1)).min(1),
  rationale: z.string().min(1),
})

const DemoteToReferencesSchema = z.object({
  move: z.literal('DEMOTE_TO_REFERENCES'),
  umbrella_skill_id: z.string().min(1),
  demote_map: z.array(z.object({
    member_id: z.string().min(1),
    target_kind: z.enum(['reference', 'template', 'script']),
    target_name: z.string().min(1),
  })).min(1),
  absorbed_member_ids: z.array(z.string().min(1)).min(1),
  rationale: z.string().min(1),
})

const RejectSchema = z.object({
  move: z.literal('REJECT'),
  reason: z.string().min(1),
})

const ProposalSchema = z.discriminatedUnion('move', [
  MergeIntoExistingSchema,
  CreateNewUmbrellaSchema,
  DemoteToReferencesSchema,
  RejectSchema,
])

type Proposal = z.infer<typeof ProposalSchema>

// ── Cluster-name validator (session-artifact prefix sniffer) ─────
//
// Mirrors the validator used by WS-B's `create_umbrella`. Class-level
// names only — reject session artifacts. The umbrella pass calls into
// the same regex set for the `CREATE_NEW_UMBRELLA` move.

const SESSION_ARTIFACT_PATTERNS = [
  /^fix-/i,
  /^debug-/i,
  /^audit-/i,
  /^today-/i,
  /\b\d{4}-\d{2}-\d{2}\b/, // dated names
  /\bpr-?\d+\b/i,           // PR-numbered
]

function isSessionArtifactName(slug: string): boolean {
  return SESSION_ARTIFACT_PATTERNS.some((re) => re.test(slug))
}

// ── Embedding clustering ─────────────────────────────────────────

/**
 * Cosine similarity on two equal-dimension vectors.
 * Vectors are expected to be unit-norm by the upstream embedder, but
 * the explicit divide handles non-normalised vectors defensively.
 */
function cosineSimilarity(a: readonly number[], b: readonly number[]): number {
  if (a.length !== b.length || a.length === 0) return 0
  let dot = 0
  let na = 0
  let nb = 0
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i]
    na += a[i] * a[i]
    nb += b[i] * b[i]
  }
  const denom = Math.sqrt(na) * Math.sqrt(nb)
  return denom === 0 ? 0 : dot / denom
}

/** Agglomerative single-linkage clustering at the given cosine
 *  threshold. Two skills join the same cluster iff their description
 *  embeddings have cosine >= threshold AND share >= 1 tag (the
 *  spec's tie-breaker to suppress false positives across unrelated
 *  domains that happen to share linguistic shape). */
export function clusterByEmbedding(
  skills: readonly UmbrellaSkill[],
  embeddings: ReadonlyMap<string, number[]>,
  tagsByRowId: ReadonlyMap<string, ReadonlySet<string>>,
  threshold: number,
): UmbrellaSkill[][] {
  const n = skills.length
  const parent = Array.from({ length: n }, (_, i) => i)
  const find = (x: number): number => {
    while (parent[x] !== x) {
      parent[x] = parent[parent[x]]
      x = parent[x]
    }
    return x
  }
  const union = (a: number, b: number) => {
    const ra = find(a)
    const rb = find(b)
    if (ra !== rb) parent[ra] = rb
  }

  for (let i = 0; i < n; i++) {
    const ei = embeddings.get(skills[i].rowId)
    if (!ei) continue
    const ti = tagsByRowId.get(skills[i].rowId)
    for (let j = i + 1; j < n; j++) {
      const ej = embeddings.get(skills[j].rowId)
      if (!ej) continue
      const tj = tagsByRowId.get(skills[j].rowId)
      // Tag overlap requirement — at least one shared tag.
      let overlaps = false
      if (ti && tj) {
        for (const t of ti) {
          if (tj.has(t)) {
            overlaps = true
            break
          }
        }
      }
      if (!overlaps) continue
      if (cosineSimilarity(ei, ej) >= threshold) union(i, j)
    }
  }

  const groups = new Map<number, UmbrellaSkill[]>()
  for (let i = 0; i < n; i++) {
    if (!embeddings.has(skills[i].rowId)) continue
    const r = find(i)
    const list = groups.get(r) ?? []
    list.push(skills[i])
    groups.set(r, list)
  }

  return [...groups.values()].filter((g) => g.length >= MIN_CLUSTER_SIZE)
}

// ── Re-extraction protection ─────────────────────────────────────

/** Returns the set of member rowIds that participated in a digest
 *  action marked `undone` within the protection window. Those rowIds
 *  are excluded from the candidate set for the run. */
function recentUndoneMemberIds(
  digestRows: Array<{ weekOf: Date; actions: unknown }>,
  now: Date,
  protectionDays: number,
): Set<string> {
  const cutoff = now.getTime() - protectionDays * 24 * 60 * 60 * 1000
  const out = new Set<string>()
  for (const row of digestRows) {
    if (row.weekOf.getTime() < cutoff) continue
    const actions = Array.isArray(row.actions) ? (row.actions as SkillCuratorAction[]) : []
    for (const a of actions) {
      if (a.kind === 'skipped') continue
      if (!a.undone) continue
      if (a.undoneAt && a.undoneAt.getTime() < cutoff) continue
      for (const id of a.absorbedMemberRowIds) out.add(id)
    }
  }
  return out
}

// ── Tags helper ──────────────────────────────────────────────────
//
// Tag overlap is required as a tie-breaker. The store does not currently
// surface per-skill tag arrays directly — they live on the originating
// memories or are inferred from `requiresConnectors`. For V2, we
// approximate tags from `(category, ...requiresConnectors)`, which
// preserves the "shared domain" intent of the gate without depending
// on a column WS-A doesn't expose.

function deriveTagSet(s: UmbrellaSkill): Set<string> {
  const tags = new Set<string>()
  if (s.category) tags.add(`category:${s.category}`)
  for (const c of s.requiresConnectors) tags.add(`connector:${c}`)
  return tags
}

// ── Diff helper ──────────────────────────────────────────────────
//
// `last_patch_diff` is stored on the umbrella row for the 30-day undo
// window. We persist a minimal unified-diff-style payload so the undo
// surface can restore the prior body verbatim.

function buildPatchDiff(before: string, after: string): string {
  // Compact representation — full before/after blobs, line-delimited.
  // A real unified diff is overkill for the V2 undo surface; the
  // restore action only needs the prior body to write back.
  return JSON.stringify({ before, after, at: new Date().toISOString() })
}

// ── Cluster proposal LLM call ────────────────────────────────────

function buildClusterPrompt(cluster: UmbrellaSkill[]): string {
  const members = cluster
    .map((s) => `- ${s.rowId} | ${s.slug} | ${s.name} | ${s.description}`)
    .join('\n')
  return PROCEDURAL_UMBRELLA_PROMPT.replace('{{MEMBERS}}', members)
}

function parseProposal(raw: string): { ok: true; proposal: Proposal } | { ok: false; error: string } {
  // Tolerate fenced JSON — strip common fence variants before parsing.
  const stripped = raw
    .trim()
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```$/i, '')
    .trim()
  let parsed: unknown
  try {
    parsed = JSON.parse(stripped)
  } catch (err) {
    return { ok: false, error: `JSON parse: ${(err as Error).message}` }
  }
  const result = ProposalSchema.safeParse(parsed)
  if (!result.success) {
    return { ok: false, error: `Zod validation: ${result.error.message}` }
  }
  return { ok: true, proposal: result.data }
}

// ── Per-cluster executor ─────────────────────────────────────────

async function executeProposal(params: {
  workspaceId: string
  cluster: UmbrellaSkill[]
  proposal: Proposal
  store: SkillUmbrellaStore
}): Promise<{ action: SkillCuratorAction | null; error?: string }> {
  const { workspaceId: _workspaceId, cluster, proposal, store } = params
  const memberByRowId = new Map(cluster.map((s) => [s.rowId, s]))

  if (proposal.move === 'REJECT') {
    return {
      action: {
        kind: 'skipped',
        reason: 'cluster_proposal_rejected',
        memberRowIds: cluster.map((s) => s.rowId),
        detail: proposal.reason,
      },
    }
  }

  // Validate absorbed_member_ids ⊆ cluster member rowIds.
  for (const id of proposal.absorbed_member_ids) {
    if (!memberByRowId.has(id)) {
      return {
        action: null,
        error: `absorbed_member_ids contains rowId ${id} not in cluster`,
      }
    }
  }

  if (proposal.move === 'MERGE_INTO_EXISTING') {
    const target = memberByRowId.get(proposal.target_skill_id)
    if (!target) {
      return { action: null, error: `target_skill_id ${proposal.target_skill_id} not in cluster` }
    }
    // The target must not also be absorbed (would archive itself).
    if (proposal.absorbed_member_ids.includes(target.rowId)) {
      return {
        action: null,
        error: `target_skill_id ${target.rowId} cannot also be absorbed`,
      }
    }
    const diff = buildPatchDiff(target.content, proposal.patched_content)
    await store.patchUmbrella(target.rowId, { content: proposal.patched_content, diff })
    for (const memberId of proposal.absorbed_member_ids) {
      await store.recordAbsorption(memberId, target.rowId)
    }
    return {
      action: {
        kind: 'merged_into_existing',
        umbrellaRowId: target.rowId,
        absorbedMemberRowIds: proposal.absorbed_member_ids,
        rationale: proposal.rationale,
      },
    }
  }

  if (proposal.move === 'CREATE_NEW_UMBRELLA') {
    if (isSessionArtifactName(proposal.new_skill_draft.slug)) {
      return {
        action: {
          kind: 'skipped',
          reason: 'cluster_proposal_rejected',
          memberRowIds: cluster.map((s) => s.rowId),
          detail: `session-artifact name rejected: ${proposal.new_skill_draft.slug}`,
        },
      }
    }
    // Pick an originating assistant from any cluster member so the new
    // umbrella inherits the visibility scope of where it was learned.
    const originatingAssistantId =
      cluster.find((m) => m.originatingAssistantId)?.originatingAssistantId ?? null
    const created = await store.createUmbrella(cluster[0].workspaceId, {
      slug: proposal.new_skill_draft.slug,
      name: proposal.new_skill_draft.name,
      description: proposal.new_skill_draft.description,
      whenToUse: proposal.new_skill_draft.when_to_use,
      content: proposal.new_skill_draft.content,
      category: proposal.new_skill_draft.category,
      requiresConnectors: proposal.new_skill_draft.requires_connectors,
      originatingAssistantId,
    })
    for (const memberId of proposal.absorbed_member_ids) {
      await store.recordAbsorption(memberId, created.rowId)
    }
    return {
      action: {
        kind: 'created_new_umbrella',
        umbrellaRowId: created.rowId,
        absorbedMemberRowIds: proposal.absorbed_member_ids,
        rationale: proposal.rationale,
      },
    }
  }

  // DEMOTE_TO_REFERENCES
  const umbrella = memberByRowId.get(proposal.umbrella_skill_id)
  if (!umbrella) {
    return {
      action: null,
      error: `umbrella_skill_id ${proposal.umbrella_skill_id} not in cluster`,
    }
  }
  if (proposal.absorbed_member_ids.includes(umbrella.rowId)) {
    return {
      action: null,
      error: `umbrella_skill_id ${umbrella.rowId} cannot also be absorbed`,
    }
  }
  // Index demote entries by member for content lookup.
  const demoteByMember = new Map(proposal.demote_map.map((d) => [d.member_id, d]))
  for (const memberId of proposal.absorbed_member_ids) {
    const member = memberByRowId.get(memberId)
    const demote = demoteByMember.get(memberId)
    if (!member || !demote) continue
    await store.addSupportFile({
      umbrellaRowId: umbrella.rowId,
      kind: demote.target_kind,
      name: demote.target_name,
      content: member.content,
      description: member.description,
    })
    await store.recordAbsorption(memberId, umbrella.rowId)
  }
  return {
    action: {
      kind: 'demoted_to_references',
      umbrellaRowId: umbrella.rowId,
      absorbedMemberRowIds: proposal.absorbed_member_ids,
      rationale: proposal.rationale,
    },
  }
}

// ── Public entry point ───────────────────────────────────────────

export type RunSkillUmbrellaPassParams = {
  workspaceId: string
  /** Used to gate the >=21-day workspace_age trigger. */
  workspaceCreatedAt: Date
  store: SkillUmbrellaStore
  digestStore: SkillUmbrellaDigestStore
  /**
   * Embedding callback — the worker wires in the real Gemini
   * `embedder.embed(texts)` here. Returns one vector per text in the
   * same order. The caller is free to cache or no-op the call (e.g.
   * empty `texts` => empty array).
   */
  getEmbeddings: (texts: string[]) => Promise<number[][]>
  /**
   * One Flash call per cluster. Pass through to the worker's
   * `callModel(prompt, ctx)`; this function does not own model
   * selection. Returning a malformed string is surfaced as a skipped
   * cluster, not a thrown error.
   */
  callModel: (prompt: string) => Promise<string>
  /** Event hook — analytics + admin alerts attach here. */
  onEvent?: (event: SkillUmbrellaEvent) => void
  /** Pluggable clock for tests. */
  now?: () => Date
  /** Override the >=20-skills gate (tests). */
  minSkillCount?: number
  /** Override the >=21-day workspace age gate (tests). */
  minWorkspaceAgeDays?: number
  /** Skip skills whose updated_at is newer than this many days ago. */
  updatedAtGraceDays?: number
  /** Cluster threshold (default 0.65). */
  clusterThreshold?: number
  /** Max clusters processed per run (default 3). */
  maxClustersPerRun?: number
  /** Re-extraction protection window (default 30 days). */
  reExtractionProtectionDays?: number
}

export type RunSkillUmbrellaPassResult = {
  workspaceId: string
  clustersProcessed: number
  actions: SkillCuratorAction[]
}

/** Returns the start-of-week Monday (UTC) for a given date — the
 *  digest groups by ISO week. */
export function startOfWeekUTC(d: Date): Date {
  const x = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()))
  const dow = x.getUTCDay() // 0 = Sun
  const offset = dow === 0 ? -6 : 1 - dow
  x.setUTCDate(x.getUTCDate() + offset)
  return x
}

export async function runSkillUmbrellaPass(
  params: RunSkillUmbrellaPassParams,
): Promise<RunSkillUmbrellaPassResult> {
  const {
    workspaceId,
    workspaceCreatedAt,
    store,
    digestStore,
    getEmbeddings,
    callModel,
    onEvent,
    now = () => new Date(),
    minSkillCount = MIN_SKILL_COUNT_DEFAULT,
    minWorkspaceAgeDays = MIN_WORKSPACE_AGE_DAYS_DEFAULT,
    updatedAtGraceDays = SKILL_UPDATED_AT_GRACE_DAYS_DEFAULT,
    clusterThreshold = CLUSTER_THRESHOLD_DEFAULT,
    maxClustersPerRun = MAX_CLUSTERS_PER_RUN_DEFAULT,
    reExtractionProtectionDays = RE_EXTRACTION_PROTECTION_DAYS_DEFAULT,
  } = params

  const currentTime = now()
  const actions: SkillCuratorAction[] = []

  // ── Trigger gate 1: workspace_age ────────────────────────────
  const ageDays = (currentTime.getTime() - workspaceCreatedAt.getTime()) / (24 * 60 * 60 * 1000)
  if (ageDays < minWorkspaceAgeDays) {
    onEvent?.({ type: 'skill_umbrella_skipped', workspaceId, reason: 'workspace_too_young' })
    return { workspaceId, clustersProcessed: 0, actions: [] }
  }

  // ── Load curator-eligible skills ─────────────────────────────
  // `listCuratorEligible` already filters background_review-origin,
  // non-pinned, in ('active','stale'). We add the >=7d updated_at
  // grace gate here so freshly-touched skills get time to settle.
  let eligible = await store.listCuratorEligible(workspaceId)
  const graceCutoff = currentTime.getTime() - updatedAtGraceDays * 24 * 60 * 60 * 1000
  eligible = eligible.filter((s) => {
    // `valid_from` is the universal-column write timestamp — updated_at
    // is not on `UmbrellaSkill` because WS-A maps it through to the
    // bi-temporal `valid_from`. Use that as the "last touched" anchor.
    const anchor = s.lastInvokedAt ?? s.validFrom
    return anchor.getTime() < graceCutoff
  })

  // ── Re-extraction protection: drop members recently undone ───
  const recentDigests = await digestStore.listForWorkspace(workspaceId, DIGEST_LOOKBACK_WEEKS)
  const protectedIds = recentUndoneMemberIds(
    recentDigests,
    currentTime,
    reExtractionProtectionDays,
  )
  eligible = eligible.filter((s) => !protectedIds.has(s.rowId))

  // ── Trigger gate 2: >=20 skills ──────────────────────────────
  if (eligible.length < minSkillCount) {
    onEvent?.({ type: 'skill_umbrella_skipped', workspaceId, reason: 'insufficient_skills' })
    return { workspaceId, clustersProcessed: 0, actions: [] }
  }

  // ── Embeddings ───────────────────────────────────────────────
  // One vector per skill, source = description. Empty input from the
  // embedder means embeddings are unavailable for this workspace —
  // skip the run, surface to operators.
  const texts = eligible.map((s) => s.description)
  let vectors: number[][] = []
  try {
    vectors = await getEmbeddings(texts)
  } catch (err) {
    onEvent?.({ type: 'skill_umbrella_skipped', workspaceId, reason: 'no_embeddings' })
    actions.push({
      kind: 'skipped',
      reason: 'no_embeddings',
      memberRowIds: eligible.map((s) => s.rowId),
      detail: (err as Error).message,
    })
    await persistDigest(digestStore, workspaceId, currentTime, actions)
    return { workspaceId, clustersProcessed: 0, actions }
  }
  if (vectors.length !== eligible.length) {
    onEvent?.({ type: 'skill_umbrella_skipped', workspaceId, reason: 'no_embeddings' })
    actions.push({
      kind: 'skipped',
      reason: 'no_embeddings',
      memberRowIds: eligible.map((s) => s.rowId),
      detail: `embedder returned ${vectors.length} vectors for ${eligible.length} inputs`,
    })
    await persistDigest(digestStore, workspaceId, currentTime, actions)
    return { workspaceId, clustersProcessed: 0, actions }
  }
  const embeddings = new Map<string, number[]>()
  const tagsByRowId = new Map<string, Set<string>>()
  for (let i = 0; i < eligible.length; i++) {
    embeddings.set(eligible[i].rowId, vectors[i])
    tagsByRowId.set(eligible[i].rowId, deriveTagSet(eligible[i]))
  }

  // ── Cluster ──────────────────────────────────────────────────
  const clusters = clusterByEmbedding(eligible, embeddings, tagsByRowId, clusterThreshold)
  if (clusters.length === 0) {
    onEvent?.({ type: 'skill_umbrella_skipped', workspaceId, reason: 'no_clusters' })
    return { workspaceId, clustersProcessed: 0, actions: [] }
  }

  // Per-run cap — process the largest clusters first (those have the
  // most consolidation value).
  const ranked = [...clusters].sort((a, b) => b.length - a.length).slice(0, maxClustersPerRun)

  // ── Per-cluster proposal + execute ───────────────────────────
  let clustersProcessed = 0
  for (const cluster of ranked) {
    const prompt = buildClusterPrompt(cluster)
    let raw: string
    try {
      raw = await callModel(prompt)
    } catch (err) {
      const failAction: SkillCuratorAction = {
        kind: 'skipped',
        reason: 'malformed_llm_output',
        memberRowIds: cluster.map((s) => s.rowId),
        detail: `callModel threw: ${(err as Error).message}`,
      }
      actions.push(failAction)
      onEvent?.({
        type: 'skill_umbrella_cluster_failed',
        workspaceId,
        reason: 'callModel threw',
        memberRowIds: cluster.map((s) => s.rowId),
      })
      continue
    }

    const parsed = parseProposal(raw)
    if (!parsed.ok) {
      const failAction: SkillCuratorAction = {
        kind: 'skipped',
        reason: 'malformed_llm_output',
        memberRowIds: cluster.map((s) => s.rowId),
        detail: parsed.error,
      }
      actions.push(failAction)
      onEvent?.({
        type: 'skill_umbrella_cluster_failed',
        workspaceId,
        reason: parsed.error,
        memberRowIds: cluster.map((s) => s.rowId),
      })
      continue
    }

    try {
      const execResult = await executeProposal({
        workspaceId,
        cluster,
        proposal: parsed.proposal,
        store,
      })
      if (execResult.error) {
        const failAction: SkillCuratorAction = {
          kind: 'skipped',
          reason: 'commit_failed',
          memberRowIds: cluster.map((s) => s.rowId),
          detail: execResult.error,
        }
        actions.push(failAction)
        onEvent?.({
          type: 'skill_umbrella_cluster_failed',
          workspaceId,
          reason: execResult.error,
          memberRowIds: cluster.map((s) => s.rowId),
        })
        continue
      }
      if (execResult.action) {
        actions.push(execResult.action)
        // `clustersProcessed` only counts COMMITTED moves. Skipped
        // outcomes (REJECT, session-artifact rejection, etc.) go into
        // `actions` for the digest but do not bump the count.
        if (execResult.action.kind !== 'skipped') {
          clustersProcessed++
          onEvent?.({
            type: 'skill_umbrella_cluster_committed',
            workspaceId,
            action: execResult.action,
          })
        }
      }
    } catch (err) {
      const failAction: SkillCuratorAction = {
        kind: 'skipped',
        reason: 'commit_failed',
        memberRowIds: cluster.map((s) => s.rowId),
        detail: `executeProposal threw: ${(err as Error).message}`,
      }
      actions.push(failAction)
      onEvent?.({
        type: 'skill_umbrella_cluster_failed',
        workspaceId,
        reason: 'executeProposal threw',
        memberRowIds: cluster.map((s) => s.rowId),
      })
    }
  }

  // ── Digest entry ─────────────────────────────────────────────
  if (actions.length > 0) {
    await persistDigest(digestStore, workspaceId, currentTime, actions)
  }

  return { workspaceId, clustersProcessed, actions }
}

async function persistDigest(
  digestStore: SkillUmbrellaDigestStore,
  workspaceId: string,
  now: Date,
  actions: SkillCuratorAction[],
): Promise<void> {
  try {
    await digestStore.append(workspaceId, startOfWeekUTC(now), actions)
  } catch (err) {
    // Digest failure is not fatal — the curator actions already
    // committed to the live tables. Log and move on.
    // eslint-disable-next-line no-console
    console.error('[skill-umbrella] digest append failed:', err)
  }
}
