/** Cloud Link carries an approved immutable projection, never raw post text. */
import { z } from 'zod'
import { feedLinkedInContextSchema } from './feed-linkedin.js'
const hash=z.string().regex(/^[a-f0-9]{64}$/)
const media=z.object({fileId:z.string().uuid(),mimeType:z.enum(['image/png','image/jpeg','image/gif','image/webp']),alt:z.string().max(2000),blockId:z.string().max(200),placement:z.enum(['inline','attachment'])}).strict()
export const feedLinkedInPayloadSchema=z.object({version:z.literal(1),revision:z.number().int().nonnegative(),authorUrn:z.string().regex(/^urn:li:(person:[\w-]+|organization:\d+)$/),projection:z.object({version:z.literal(1),mode:z.enum(['post','link_post']),text:z.string().max(3000),commentary:z.string().max(6000),visibleLength:z.number().int().max(3000),wireLength:z.number().int().max(6000),media:z.array(media).max(20),article:z.object({sourceUrl:z.string().url(),title:z.string().max(2000),description:z.string().max(10000),thumbnailFileId:z.string().uuid().nullable().optional()}).strict().optional(),context:feedLinkedInContextSchema,warnings:z.array(z.object({code:z.enum(['formatting_loss','inline_attachments']),blockId:z.string().optional()}).strict()).max(2000),blockers:z.array(z.never()).max(0)}).strict(),assets:z.array(z.object({fileId:z.string().uuid(),sourceHash:hash,hash,mimeType:z.enum(['image/png','image/jpeg','image/gif']),size:z.number().int().positive().max(20*1024*1024),derivativeVersion:z.literal(1)}).strict()).max(20)}).strict()
export const feedLinkedInCloudRequestSchema=z.object({sessionId:z.string().uuid(),confirmationId:z.string().uuid(),expectedRevision:z.number().int().nonnegative(),destinationId:z.string().uuid(),previewHash:hash,idempotencyKey:z.string().min(1).max(180),publicReleaseRevision:z.number().int().nonnegative(),payload:feedLinkedInPayloadSchema}).strict().superRefine((value,ctx)=>{
 if(value.payload.revision!==value.expectedRevision||value.publicReleaseRevision!==value.expectedRevision||value.payload.projection.context.destinationId!==value.destinationId||value.payload.projection.context.mode!==value.payload.projection.mode)ctx.addIssue({code:'custom',message:'Exact revision and destination required'})
 if(value.payload.assets.reduce((sum,a)=>sum+a.size,0)>100*1024*1024)ctx.addIssue({code:'custom',message:'Approved assets exceed transfer limit'})
})
export type FeedLinkedInCloudRequest=z.infer<typeof feedLinkedInCloudRequestSchema>
