export {
  DEAL_STAGES,
  type DealStage,
  type CrmExternalRef,
  CRM_CUSTOM_FIELD_TYPES,
  type CrmCustomFieldType,
  type CrmCustomFieldEntityKind,
  type CrmCustomFieldDefinition,
  type CrmCustomFieldWriteResult,
  type CompanyRecord,
  type CompanyListRow,
  type CompanyListFilters,
  type CompanyUpdateFields,
  type ContactRecord,
  type ContactListRow,
  type ContactListFilters,
  type ContactUpdateFields,
  type DealRecord,
  type DealListRow,
  type DealListFilters,
  type DealUpdateFields,
  type CrmStore,
} from './types.js'
export {
  createCrmTools,
  type CrmToolEvent,
  type CrmToolOptions,
} from './tools.js'
