/**
 * `skill_manage` — the four-action curator write tool.
 *
 * Invoked only by the background-review worker's restricted query-loop, NOT
 * by main chat. The worker forks an LLM agent whose tool set is
 * `[skills_list, skill_view, skill_manage]`; this is the only writer. The
 * factory closes over a workspace-scoped binding (`workspaceId`,
 * `originatingAssistantId`, `leaseHolderId`) so the action handlers don't
 * need to derive context from a generic `ToolContext` — the worker can pass
 * its own context to every invocation.
 *
 * Four actions, ordered as the model is told to prefer them:
 *
 *   1. `patch_skill`     — adjust the in-play skill (most common)
 *   2. `update_umbrella` — broaden an existing umbrella (subsection / pitfall)
 *   3. `add_support_file`— add a reference / template / script under existing
 *   4. `create_umbrella` — create a new class-level umbrella (last resort)
 *
 * Each action enforces the routing-by-authorship rule from the spec:
 *
 *   * `auto-generated` skill → direct write to `workspace_skills` (+ audit)
 *   * `user` / `community` skill → stage to `pending_approvals`
 *     (`kind='staged_skill_update'`)
 *   * `create_umbrella` (always new) → stage to `pending_approvals`
 *     (`kind='staged_skill_creation'`)
 *
 * Spec: `docs/architecture/engine/skill-system.md` →
 *   "Skill auto-generation" → "Approval routing — by skill authorship".
 *
 * [COMP:skills/manage-tool]
 */

import { z } from 'zod'
import { buildTool, type Tool } from '../tools/types.js'
import { toolFailure } from '../tools/tool-failure.js'
import { extractPointers, type SkillFilePointerKind } from './loader.js'
import { validateClassLevelName } from './class-name-validator.js'

// ── Port shapes — kept narrow so packages/core stays DB-driver-free ─

/**
 * The subset of `WorkspaceSkill` (mig 168) the tool reads. Mirrors the
 * canonical store in `packages/api/src/db/skill-store.ts` but only the
 * fields the routing decision needs.
 */
export type SkillManageSkill = {
  rowId: string
  workspaceId: string
  slug: string
  name: string
  source: 'builtin' | 'user' | 'community' | 'auto-generated'
  writeOrigin: 'foreground' | 'background_review'
  pinned: boolean
  state: 'active' | 'stale' | 'archived'
}

/** Write port for direct skill mutations. The factory binds a workspace-
 *  scoped instance; method calls require the leaseHolderId so the
 *  acquire-then-edit invariant is enforced. */
export type SkillManageSkillStore = {
  /** Look up the row that backs a `(workspaceId, skillId)` pair. Returns
   *  null if the skill is gone, has been bi-temporally closed, or never
   *  belonged to this workspace — the action handlers short-circuit. */
  getSkillForWorkspace(workspaceId: string, rowId: string): Promise<SkillManageSkill | null>

  /** Direct patch to the body. Used when the target is `auto-generated`.
   *  The caller has already verified write_origin / pinned / state gates
   *  and holds the review lease. Stores the diff in `last_patch_diff` for
   *  the 30-day undo window. */
  applyPatch(params: {
    rowId: string
    workspaceId: string
    newContent: string
    diff: string | null
    leaseHolderId: string
  }): Promise<void>

  /** Insert a brand-new auto-generated umbrella. Direct-write path used
   *  when `create_umbrella` is allowed to bypass the approval queue (today
   *  it never is — every create routes to approvals; method kept for the
   *  future "trusted-curator" mode). */
  createAutoGenerated(params: {
    workspaceId: string
    slug: string
    name: string
    description: string
    content: string
    originatingAssistantId: string | null
  }): Promise<{ rowId: string }>
}

/** Write port for skill support files (`workspace_skill_files`). */
export type SkillManageFileStore = {
  list(workspaceSkillId: string): Promise<
    Array<{ kind: SkillFilePointerKind; name: string; content: string }>
  >
  upsert(params: {
    workspaceSkillId: string
    kind: SkillFilePointerKind
    name: string
    content: string
    description?: string | null
    leaseHolderId: string
  }): Promise<void>
}

/** Write port for the unified approvals queue. Targets
 *  `pending_approvals` rows with `kind='staged_skill_*'`. */
export type SkillManageApprovalsStore = {
  createStagedSkillUpdate(params: {
    workspaceId: string
    targetSkillId: string
    proposedPatch: {
      newContent?: string
      diff?: string
      addedFiles?: Array<{ kind: SkillFilePointerKind; name: string; content: string; description?: string }>
    }
    originatingAssistantId: string | null
    requestedByUserId?: string | null
  }): Promise<{ approvalId: string }>

  createStagedSkillCreation(params: {
    workspaceId: string
    proposedUmbrella: {
      slug: string
      name: string
      description: string
      /** Optional on the PORT, required on the tool's own input schema:
       *  approvals staged before the field existed carry no trigger, and
       *  approve-time must still be able to materialise them. */
      whenToUse?: string
      content: string
      supportFiles?: Array<{ kind: SkillFilePointerKind; name: string; content: string; description?: string }>
    }
    originatingAssistantId: string | null
    /** Induction-provenance passthrough (origin-aware induction) — rides the
     *  approval_payload so approve-time governance can route provenance and
     *  render the attach offer. Absent on interactive-session inductions. */
    origin?: string
    sourceWorkflowIds?: string[]
    attachTo?: { workflowId: string; stepId?: string }
  }): Promise<{ approvalId: string }>

  /** Dedupe reads — a pending proposal for the same target blocks staging
   *  another (at most ONE pending `staged_skill_update` per target skill,
   *  and ONE pending `staged_skill_creation` per proposed slug, per
   *  workspace). Without this gate a busy session re-stages a
   *  near-identical proposal every review tick until a human acts. */
  findPendingStagedSkillUpdate(params: {
    workspaceId: string
    targetSkillId: string
  }): Promise<{ approvalId: string } | null>

  findPendingStagedSkillCreation(params: {
    workspaceId: string
    slug: string
  }): Promise<{ approvalId: string } | null>
}

/** Per-assistant enablement binding. Used when an `auto-generated` skill is
 *  freshly created to enable it for the originating assistant. */
export type SkillManageEnablementStore = {
  enableForOriginating(params: {
    workspaceSkillId: string
    assistantId: string
    enabledByUserId: string
  }): Promise<void>
}

// ── Factory deps & action input schema ────────────────────────────

export type SkillManageDeps = {
  workspaceId: string
  /** Originating assistant — the one whose session triggered this review.
   *  Pinned to enablement rows on direct creates so the curator can wire
   *  fresh skills to "the assistant that learned the pattern". */
  originatingAssistantId: string | null
  /** The lease holder UUID the curator must already hold on every target
   *  before patches are accepted. Surfaced to the store so it can include
   *  the lease holder in its WHERE clause — first-writer-wins. */
  leaseHolderId: string
  /** Approver user id used on direct writes that need an attributed actor
   *  (e.g. enablement insert). For staged_skill_* approval rows the
   *  approver is the workspace owner; this id is only used for direct
   *  mutations that touch RLS-gated tables on behalf of the system. */
  systemActorUserId: string
  /** Origin-aware induction context for `create_umbrella` staging. Set by
   *  the review worker when the reviewed session is workflow-origin so the
   *  staged creation carries workflow provenance + the attach offer. Absent
   *  (interactive sessions, direct tool use) → staging is unchanged. */
  stagingContext?: {
    origin?: string
    sourceWorkflowIds?: string[]
    attachTo?: { workflowId: string; stepId?: string }
  }

  workspaceSkillStore: SkillManageSkillStore
  fileStore: SkillManageFileStore
  approvalsStore: SkillManageApprovalsStore
  enablementStore: SkillManageEnablementStore
}

const PATCH_SCHEMA = z
  .object({
    newContent: z.string().min(1).optional(),
    diff: z.string().min(1).optional(),
  })
  .refine((p) => p.newContent !== undefined || p.diff !== undefined, {
    message: 'patch must include newContent and/or diff',
  })

const FILE_SCHEMA = z.object({
  kind: z.enum(['reference', 'template', 'script']),
  name: z
    .string()
    .min(1)
    .max(200)
    // The DB has a (workspaceSkillId, kind, name) UNIQUE; names must be
    // pointer-addressable so we forbid the characters that would break the
    // `{{kind:name}}` syntax.
    .refine((n) => !/[{}\r\n]/.test(n), 'name may not contain newlines or curly braces'),
  content: z.string().min(1).max(50_000),
  description: z.string().max(500).optional(),
})

const UMBRELLA_SCHEMA = z.object({
  name: z.string().min(1).max(100),
  description: z.string().min(1).max(500),
  // REQUIRED on this path, deliberately. `when_to_use` is the only field the
  // skill listing gives the model to select on, and a skill without one is
  // effectively unreachable: in prod, 67 of 72 workspace skills had no
  // trigger and 2 had ever been invoked. Every one of those was born here,
  // through a schema that had no field for it. A human authoring a skill in
  // the UI may still omit it (`CreateSkillInput.whenToUse` stays optional) —
  // they can see and fix their own library. An assistant proposing one
  // cannot, so it must say when the skill fires before it may create it.
  whenToUse: z
    .string()
    .min(1)
    .max(300)
    .describe('The trigger condition: what the user says or does that should make this skill fire.'),
  content: z.string().min(1).max(50_000),
  supportFiles: z.array(FILE_SCHEMA).max(20).optional(),
})

const INPUT_SCHEMA = z.discriminatedUnion('action', [
  z.object({
    action: z.literal('patch_skill'),
    skillId: z.string().uuid(),
    patch: PATCH_SCHEMA,
  }),
  z.object({
    action: z.literal('update_umbrella'),
    skillId: z.string().uuid(),
    patch: PATCH_SCHEMA,
  }),
  z.object({
    action: z.literal('add_support_file'),
    skillId: z.string().uuid(),
    file: FILE_SCHEMA,
  }),
  z.object({
    action: z.literal('create_umbrella'),
    umbrella: UMBRELLA_SCHEMA,
  }),
])

export type SkillManageInput = z.infer<typeof INPUT_SCHEMA>

export type SkillManageActionTaken =
  | 'direct'
  | 'queued_for_approval'
  /** A pending approval for the same target already exists — staging was
   *  skipped, `approvalId` names the existing row. Not an error: the
   *  worker treats it as a no-op (no cap spend, no failure log). */
  | 'skipped_pending_approval'

export type SkillManageResult =
  | {
      actionTaken: SkillManageActionTaken
      targetSkillId: string
      approvalId?: string
    }
  | { error: string }

// ── The tool description: visible to the worker's LLM ────────────

/**
 * Description copy mirrors the spec's "Update-first preference order" so the
 * curator agent sees the preference order at the call site — exactly where
 * it matters. Kept tight: the L1 system prompt is tool-agnostic per the
 * project's tool-awareness rule, so the entire steering for this tool
 * lives here.
 */
const DESCRIPTION = `Manage the workspace's skill library. Use this tool to record what you learned in this conversation, preferring small updates to existing skills over creating new ones.

Choose the action in this order — try each one and only fall through when it does not fit:

1. patch_skill — Patch the in-play skill. Use when the conversation surfaced a refinement to a skill that was loaded for this session (a missing step, a subtle preference, a fixed mistake).

2. update_umbrella — Broaden an existing umbrella skill. Use when the lesson belongs under a class-level skill that exists but does not yet cover this subsection / pitfall / trigger. Patch its body to add the missing piece.

3. add_support_file — Add a reference, template, or script under an existing skill. Use when the lesson is concrete enough to be a standalone artefact (a template the user reused, a transcript worth quoting, a checklist the user followed). Body pointers use {{reference:name}} / {{template:name}} / {{script:name}}.

4. create_umbrella — Create a new class-level umbrella. ONLY when nothing above fits. The name must describe a class of task — not a session-specific bug, error, date, or PR number. Names like "fix-...", "debug-...", "audit-...", "today-...", "2026-...", "pr-...", or anything containing a literal error message will be rejected.

whenToUse is required on create and is the single most important field you write. It is the only part of the skill anyone sees when deciding whether to open it, so state the TRIGGER, not the topic: what the user says or does that should make this skill fire. Write "when the user asks to log a diary entry, add a task, or sync the vault", not "diary and task management". A skill whose whenToUse merely restates its name will never be selected.

Routing is automatic — you do not need to consider it. Auto-generated skills are patched directly; user-authored and community skills are queued for the workspace owner's approval; new umbrella creations are always queued. If an equivalent proposal is already waiting for the owner's decision, the tool skips staging a duplicate and reports skipped_pending_approval. The tool result tells you which path was taken.`

// ── Factory ───────────────────────────────────────────────────────

/**
 * Build the `skill_manage` tool bound to a workspace context.
 *
 * The factory closes over `workspaceId`, `originatingAssistantId`, and
 * `leaseHolderId` so the action handlers don't need to derive context from
 * the generic `ToolContext` the query loop hands them. This makes the tool
 * testable in isolation — tests pass fake stores and exercise the routing
 * logic without spinning up a query loop.
 */
export function createSkillManageTool(deps: SkillManageDeps): Tool {
  return buildTool({
    name: 'skill_manage',
    description: DESCRIPTION,
    inputSchema: INPUT_SCHEMA,
    // Writes — never concurrency-safe, never read-only.
    isConcurrencySafe: false,
    isReadOnly: false,
    requiresConfirmation: false,

    async execute(input) {
      // Defensive parse — the production tool executor will have validated
      // already, but this is invoked from worker contexts that bypass the
      // executor's wrapping. Re-parse so a malformed input from the LLM
      // produces a structured error result instead of an unhandled throw.
      const parsed = INPUT_SCHEMA.safeParse(input)
      if (!parsed.success) {
        // Shared first-party failure frame: the zod issues as `path: message`
        // lines, plus "nothing was saved" and the retry verdict.
        return toolFailure(parsed.error, { tool: 'skill_manage', mutating: true })
      }
      try {
        const result = await executeAction(parsed.data, deps)
        const isError =
          'error' in result && typeof (result as { error?: unknown }).error === 'string'
        return { data: result, isError: isError ? true : undefined }
      } catch (err) {
        return toolFailure(err, {
          tool: 'skill_manage',
          action: `\`skill_manage\` (action \`${parsed.data.action}\`)`,
          mutating: true,
        })
      }
    },
  })
}

/**
 * Message-first copy for the write gates the four actions share
 * (docs/architecture/engine/tool-executor.md → "Failure copy").
 *
 * These used to be a bare diagnosis (`Skill <id> is pinned; auto-curation is
 * disabled for pinned skills.`) — true, but silent on whether anything was
 * written, what to do instead, and whether the identical call could ever
 * work, so the curator re-issued it. One frame now carries all four:
 * WHAT did not happen on WHICH row · WHY · NEXT · RETRY VERDICT.
 */
function writeRefused(params: {
  /** What the action was doing, e.g. `patch`, `add a support file to`. */
  verb: string
  rowId: string
  why: string
  next: string
  verdict: string
}): { error: string } {
  return {
    error: `skill_manage did not ${params.verb} skill ${params.rowId}: ${params.why}. Nothing was changed. ${params.next} ${params.verdict}`,
  }
}

/**
 * The four skill-state gates, identical for `patch_skill` /
 * `update_umbrella` / `add_support_file` — one place so the two call sites
 * cannot drift apart on the remedy they name.
 */
function skillStateRefusal(
  verb: string,
  rowId: string,
  gate: 'not_found' | 'pinned' | 'archived' | 'builtin',
): { error: string } {
  switch (gate) {
    case 'not_found':
      return writeRefused({
        verb,
        rowId,
        why:
          'that skill row id was not found in this workspace (a row id is the `workspace_skills` id, ' +
          'not the slug the listing shows, and it never crosses workspaces)',
        next: 'Call skills_list to re-resolve the id against this workspace\'s current library, then act on that row.',
        verdict: 'Do NOT retry this exact id.',
      })
    case 'pinned':
      return writeRefused({
        verb,
        rowId,
        why: 'the skill is pinned, and pinning switches auto-curation off for that skill deliberately',
        next: 'Pick another target (skills_list shows what is curatable), or leave this lesson for the workspace owner to fold in by hand.',
        verdict: 'Retrying will keep failing for as long as the skill is pinned.',
      })
    case 'archived':
      return writeRefused({
        verb,
        rowId,
        why: 'the skill is archived, and an archived skill is out of play until a workspace member restores it',
        next: 'Act on an active skill instead, or propose a new class-level one with create_umbrella.',
        verdict: 'Retrying will keep failing while it is archived.',
      })
    case 'builtin':
      return writeRefused({
        verb,
        rowId,
        why: 'it is a built-in skill that ships on disk, so no runtime write can reach it',
        next: 'Put the lesson in a workspace skill instead — patch an auto-generated one, or propose a new class-level one with create_umbrella.',
        verdict: 'Do NOT retry this id.',
      })
  }
}

// ── Action dispatch ───────────────────────────────────────────────

async function executeAction(
  input: SkillManageInput,
  deps: SkillManageDeps,
): Promise<SkillManageResult> {
  switch (input.action) {
    case 'patch_skill':
    case 'update_umbrella':
      // patch_skill and update_umbrella share plumbing — the distinction is
      // semantic ("update the in-play skill" vs "broaden the umbrella"); the
      // gates and routing are identical. Each gets its own dispatch entry
      // so the description copy stays distinct + analytics events can
      // attribute which call shape the curator chose.
      return runPatch(deps, input.skillId, input.patch, input.action)

    case 'add_support_file':
      return runAddSupportFile(deps, input.skillId, input.file)

    case 'create_umbrella':
      return runCreateUmbrella(deps, input.umbrella)
  }
}

// ── patch_skill / update_umbrella ─────────────────────────────────

async function runPatch(
  deps: SkillManageDeps,
  rowId: string,
  patch: { newContent?: string; diff?: string },
  _kind: 'patch_skill' | 'update_umbrella',
): Promise<SkillManageResult> {
  const skill = await deps.workspaceSkillStore.getSkillForWorkspace(deps.workspaceId, rowId)
  if (!skill) {
    return skillStateRefusal('patch', rowId, 'not_found')
  }
  if (skill.pinned) {
    return skillStateRefusal('patch', rowId, 'pinned')
  }
  if (skill.state === 'archived') {
    return skillStateRefusal('patch', rowId, 'archived')
  }

  // ── Routing-by-authorship ──
  // auto-generated → direct write; anything else (user/community) → stage.
  // Built-in skills live on disk and can never be patched at runtime — the
  // store should never return source='builtin' rows, but we guard anyway.
  if (skill.source === 'builtin') {
    return skillStateRefusal('patch', rowId, 'builtin')
  }

  // Optional pointer validation — only if newContent was provided.
  if (patch.newContent !== undefined) {
    const validation = await validatePointersAgainstSkill(skill.rowId, patch.newContent, deps)
    if (!validation.ok) {
      return {
        error:
          `skill_manage did not patch skill ${rowId}: ${validation.reason} Nothing was changed. ` +
          'The same body will be rejected the same way.',
      }
    }
  }

  if (skill.source === 'auto-generated') {
    if (skill.writeOrigin !== 'background_review') {
      // Defensive: source/write_origin can drift if a manual UPDATE bypasses
      // the application stamping. The invariant is that the curator
      // only ever touches background_review-origin rows.
      return writeRefused({
        verb: 'patch',
        rowId,
        why:
          `its row carries source='auto-generated' with write_origin='${skill.writeOrigin}', and the curator may only ` +
          "write rows whose write_origin is 'background_review'",
        next: 'Pick a different target skill; this row needs a human to correct its provenance before anything writes to it.',
        verdict: 'Retrying will keep failing until that row is fixed.',
      })
    }
    await deps.workspaceSkillStore.applyPatch({
      rowId: skill.rowId,
      workspaceId: deps.workspaceId,
      newContent: patch.newContent ?? '',
      diff: patch.diff ?? null,
      leaseHolderId: deps.leaseHolderId,
    })
    return { actionTaken: 'direct', targetSkillId: skill.rowId }
  }

  // user / community → queue for approval. Dedupe first: while a proposal
  // for this skill sits unresolved, a busy session would re-stage a
  // near-identical one every review tick.
  const pending = await deps.approvalsStore.findPendingStagedSkillUpdate({
    workspaceId: deps.workspaceId,
    targetSkillId: skill.rowId,
  })
  if (pending) {
    return {
      actionTaken: 'skipped_pending_approval',
      targetSkillId: skill.rowId,
      approvalId: pending.approvalId,
    }
  }
  const { approvalId } = await deps.approvalsStore.createStagedSkillUpdate({
    workspaceId: deps.workspaceId,
    targetSkillId: skill.rowId,
    proposedPatch: {
      newContent: patch.newContent,
      diff: patch.diff,
    },
    originatingAssistantId: deps.originatingAssistantId,
  })
  return { actionTaken: 'queued_for_approval', targetSkillId: skill.rowId, approvalId }
}

// ── add_support_file ──────────────────────────────────────────────

async function runAddSupportFile(
  deps: SkillManageDeps,
  rowId: string,
  file: { kind: SkillFilePointerKind; name: string; content: string; description?: string },
): Promise<SkillManageResult> {
  const skill = await deps.workspaceSkillStore.getSkillForWorkspace(deps.workspaceId, rowId)
  if (!skill) {
    return skillStateRefusal('add a support file to', rowId, 'not_found')
  }
  if (skill.pinned) {
    return skillStateRefusal('add a support file to', rowId, 'pinned')
  }
  if (skill.state === 'archived') {
    return skillStateRefusal('add a support file to', rowId, 'archived')
  }
  if (skill.source === 'builtin') {
    return skillStateRefusal('add a support file to', rowId, 'builtin')
  }

  // Validate dangling pointers inside the file content itself. Only this
  // skill's existing files plus the file being added are in scope. (The
  // file may reference itself or a sibling — but cross-skill references
  // are intentionally not supported.)
  const existing = await deps.fileStore.list(skill.rowId)
  const allowedKeys = new Set(existing.map((f) => `${f.kind}:${f.name}`))
  allowedKeys.add(`${file.kind}:${file.name}`) // self-reference is fine
  const dangling = extractPointers(file.content).filter(
    (p) => !allowedKeys.has(`${p.kind}:${p.name}`),
  )
  if (dangling.length > 0) {
    return {
      error:
        `skill_manage did not add "${file.kind}:${file.name}" to skill ${rowId}: the file content references ` +
        `missing support file(s) — ${dangling.map((d) => `${d.kind}:${d.name}`).join(', ')}. Nothing was saved. ` +
        'Add each of those with its own add_support_file call first, or delete the {{kind:name}} pointer from this ' +
        'content. Re-sending this exact content will be rejected the same way.',
    }
  }

  if (skill.source === 'auto-generated') {
    if (skill.writeOrigin !== 'background_review') {
      return writeRefused({
        verb: 'add a support file to',
        rowId,
        why:
          `its row carries source='auto-generated' with write_origin='${skill.writeOrigin}', and the curator may only ` +
          "write rows whose write_origin is 'background_review'",
        next: 'Pick a different target skill; this row needs a human to correct its provenance before anything writes to it.',
        verdict: 'Retrying will keep failing until that row is fixed.',
      })
    }
    await deps.fileStore.upsert({
      workspaceSkillId: skill.rowId,
      kind: file.kind,
      name: file.name,
      content: file.content,
      description: file.description ?? null,
      leaseHolderId: deps.leaseHolderId,
    })
    return { actionTaken: 'direct', targetSkillId: skill.rowId }
  }

  // Same dedupe gate as the patch path — an added file rides the same
  // `staged_skill_update` kind, so one pending proposal per skill blocks
  // both shapes.
  const pending = await deps.approvalsStore.findPendingStagedSkillUpdate({
    workspaceId: deps.workspaceId,
    targetSkillId: skill.rowId,
  })
  if (pending) {
    return {
      actionTaken: 'skipped_pending_approval',
      targetSkillId: skill.rowId,
      approvalId: pending.approvalId,
    }
  }
  const { approvalId } = await deps.approvalsStore.createStagedSkillUpdate({
    workspaceId: deps.workspaceId,
    targetSkillId: skill.rowId,
    proposedPatch: {
      addedFiles: [
        {
          kind: file.kind,
          name: file.name,
          content: file.content,
          description: file.description,
        },
      ],
    },
    originatingAssistantId: deps.originatingAssistantId,
  })
  return { actionTaken: 'queued_for_approval', targetSkillId: skill.rowId, approvalId }
}

// ── create_umbrella ───────────────────────────────────────────────

async function runCreateUmbrella(
  deps: SkillManageDeps,
  umbrella: {
    name: string
    description: string
    whenToUse: string
    content: string
    supportFiles?: Array<{ kind: SkillFilePointerKind; name: string; content: string; description?: string }>
  },
): Promise<SkillManageResult> {
  // Class-level naming validator — only runs on create. Reject + bubble up
  // the reason. This is an apply-time error: the worker logs it as
  // `skill_review_action_failed` and skips the action (it is not re-prompted;
  // the single LLM re-prompt is plan-shape-only, in `skill-review-llm.ts`).
  const nameCheck = validateClassLevelName(umbrella.name)
  if (!nameCheck.ok) {
    return {
      error:
        `skill_manage did not create the umbrella "${umbrella.name}": the name was rejected by the class-level ` +
        `naming rule — ${nameCheck.reason} Nothing was staged for approval. Re-send create_umbrella with a name ` +
        'that describes the CLASS of task. Re-sending this exact name will be rejected the same way.',
    }
  }

  // Validate dangling pointers in body against the proposed support files —
  // a newly-created umbrella can only point at files it ships with.
  const proposedFileKeys = new Set(
    (umbrella.supportFiles ?? []).map((f) => `${f.kind}:${f.name}`),
  )
  const dangling = extractPointers(umbrella.content).filter(
    (p) => !proposedFileKeys.has(`${p.kind}:${p.name}`),
  )
  if (dangling.length > 0) {
    return {
      error:
        `skill_manage did not create the umbrella "${umbrella.name}": its body references support file(s) not in ` +
        `the proposal — ${dangling.map((d) => `${d.kind}:${d.name}`).join(', ')}. Nothing was staged for approval. ` +
        'A new umbrella can only point at files it ships with, so add each of those to this call\'s `supportFiles` ' +
        'or drop the {{kind:name}} pointer from the body. Re-sending this exact proposal will be rejected the same way.',
    }
  }

  // Slugify name → match the existing slug convention from routes/skills.ts.
  const slug = slugify(umbrella.name)
  if (!slug) {
    return {
      error:
        `skill_manage did not create the umbrella "${umbrella.name}": the name has no alphanumeric character, so it ` +
        'slugifies to nothing and could never be addressed. Nothing was staged for approval. Re-send create_umbrella ' +
        'with a name containing letters or digits. Re-sending this exact name will be rejected the same way.',
    }
  }

  // Dedupe on the proposed slug: the same umbrella re-derived from an
  // overlapping transcript on the next tick must not stack a second
  // pending creation.
  const pending = await deps.approvalsStore.findPendingStagedSkillCreation({
    workspaceId: deps.workspaceId,
    slug,
  })
  if (pending) {
    return {
      actionTaken: 'skipped_pending_approval',
      targetSkillId: pending.approvalId,
      approvalId: pending.approvalId,
    }
  }

  // Every create goes through the approvals queue. The spec is explicit:
  // "create_umbrella (always new) → pending_approvals (kind=staged_skill_creation)".
  const { approvalId } = await deps.approvalsStore.createStagedSkillCreation({
    workspaceId: deps.workspaceId,
    proposedUmbrella: {
      slug,
      name: umbrella.name,
      description: umbrella.description,
      whenToUse: umbrella.whenToUse,
      content: umbrella.content,
      supportFiles: umbrella.supportFiles,
    },
    originatingAssistantId: deps.originatingAssistantId,
    ...(deps.stagingContext?.origin ? { origin: deps.stagingContext.origin } : {}),
    ...(deps.stagingContext?.sourceWorkflowIds?.length
      ? { sourceWorkflowIds: deps.stagingContext.sourceWorkflowIds }
      : {}),
    ...(deps.stagingContext?.attachTo ? { attachTo: deps.stagingContext.attachTo } : {}),
  })
  return {
    actionTaken: 'queued_for_approval',
    // No rowId yet — the row is created at approve-time. Use the approval
    // ID as the target identifier so the curator can refer to it.
    targetSkillId: approvalId,
    approvalId,
  }
}

// ── Helpers ───────────────────────────────────────────────────────

async function validatePointersAgainstSkill(
  rowId: string,
  newContent: string,
  deps: SkillManageDeps,
): Promise<{ ok: true } | { ok: false; reason: string }> {
  const pointers = extractPointers(newContent)
  if (pointers.length === 0) return { ok: true }
  const existing = await deps.fileStore.list(rowId)
  const have = new Set(existing.map((f) => `${f.kind}:${f.name}`))
  const dangling = pointers.filter((p) => !have.has(`${p.kind}:${p.name}`))
  if (dangling.length === 0) return { ok: true }
  return {
    ok: false,
    reason:
      `Patch body references missing support file(s): ${dangling.map((d) => `${d.kind}:${d.name}`).join(', ')}. ` +
      'Add the support file(s) first, or remove the pointer.',
  }
}

function slugify(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}
